In [1]:
################
# Tabular ARGN #
################

## Authors:             Ricardo Zambrano
## email:               rzambrano@gmail.com
## Date:               2026-03-14

## reference:           "TabularARGN: A flexible and Efficient Auto-Regressive Framework for Generating high-Fidelity Synthetic Data"
##                      Tiwald et al. (2025)
##                      https://arxiv.org/pdf/2501.12012

######################
# Tabular ARGN       #
######################

## Author:             Ricardo Zambrano
## Email:              rzambrano@gmail.com
## Date:               2026-03-14
## Reference:          "TabularARGN: A Flexible and Efficient Auto-Regressive Framework
##                      for Generating High-Fidelity Synthetic Data"
##                      Tiwald et al. (2025)
##                      https://arxiv.org/abs/[arxiv-id]  # fill this in

#################
# Session Setup #
#################

# ── Standard Library ──────────────────────────────────────────────────────────
import os
import random
from pathlib import Path

from typing import Protocol

from datetime import date, datetime

# ── Numerical & Data ──────────────────────────────────────────────────────────
import numpy as np
import polars as pl
import pandas as pd

# ── Visualization ─────────────────────────────────────────────────────────────
import matplotlib.pyplot as plt

# ── PyTorch ───────────────────────────────────────────────────────────────────
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# ── Experiment Tracking ───────────────────────────────────────────────────────
import wandb
import mlflow
from omegaconf import DictConfig, OmegaConf
import hydra

# ── Evaluation ────────────────────────────────────────────────────────────────
from sklearn.metrics import f1_score, roc_auc_score
import optuna

# ── Reproducibility ───────────────────────────────────────────────────────────
SEED = 42

def set_seed(seed: int = SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed()

# ── Hardcoded Variables ────────────────────────────────────────────────────────

# -- None --

c:\Users\rzamb\Documents\tabular_nn\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# ── Working Directory ──────────────────────────────────────────────────────────

current_dir = Path.cwd().resolve()
print(current_dir)

target_dir = Path(r"c:\Users\rzamb\Documents\tabular_nn").resolve()

if current_dir != target_dir:

    # Get the path object for two levels up
    two_levels_up = current_dir.parents[0]

    # Change the working directory to the new path
    os.chdir(two_levels_up)

# Optional: Print new working directory to confirm the change
print(f"New working directory: {Path.cwd()}")

C:\Users\rzamb\Documents\tabular_nn\notebooks
New working directory: C:\Users\rzamb\Documents\tabular_nn

In [3]:
####################
# Helper Functions #
####################

# -- None --

In [4]:
####################
# Data Loading     #
####################

insurance_data = pd.read_csv("./data/raw/insurance/insurance.csv")

In [5]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
insurance_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [8]:
beijing_data = pd.read_csv("./data/raw/beijing/PRSA_Data_Dingling_20130301-20170228.csv")

In [9]:
beijing_data.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,3.0,NaN,200.0,82.0,-2.3,1020.8,-19.7,0.0,E,0.5,Dingling
1,2,2013,3,1,1,7.0,7.0,3.0,NaN,200.0,80.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Dingling
2,3,2013,3,1,2,5.0,5.0,3.0,2.0,200.0,79.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Dingling
3,4,2013,3,1,3,6.0,6.0,3.0,NaN,200.0,79.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Dingling
4,5,2013,3,1,4,5.0,5.0,3.0,NaN,200.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Dingling

In [10]:
beijing_data["sample_date"] = pd.to_datetime({
    'year': beijing_data['year'],
    'month': beijing_data['month'],
    'day': beijing_data['day']
})

In [11]:
beijing_data = beijing_data.drop(columns=["year", "month", "day"])

In [12]:
beijing_data.dtypes

No                      int64
hour                    int64
PM2.5                 float64
PM10                  float64
SO2                   float64
NO2                   float64
CO                    float64
O3                    float64
TEMP                  float64
PRES                  float64
DEWP                  float64
RAIN                  float64
wd                     object
WSPM                  float64
station                object
sample_date    datetime64[ns]
dtype: object

In [13]:
####################
# Data Wrangling   #
####################

In [14]:
# Introducing a null values in different formats

insurance_data.iloc[0,0] = pd.NA
insurance_data.iloc[1,0] = np.nan
insurance_data.iloc[2,1] = None

# Inserting an artificial person with a number of children disconnected   from the sequence 1->5
insurance_data.iloc[3,3] = 14

# Rounding BMI to get a BINNED strategy
insurance_data["bmi"] = insurance_data["bmi"].round(1)

In [15]:
insurance_data.iloc[1317,:]

age              18.0
sex              male
bmi              53.1
children            0
smoker             no
region      southeast
charges     1163.4627
Name: 1317, dtype: object

In [16]:
df_pl = pl.from_pandas(insurance_data).clone()

In [17]:
df_pl[3,3] = 14

In [18]:
df_pl = df_pl.with_columns(
    pl.col("bmi").round(2)
)

In [19]:
# Inspecting how Polars casted missing values in a variety of formats

df_pl.head()

shape: (5, 7)
┌──────┬────────┬──────┬──────────┬────────┬───────────┬─────────────┐
│ age  ┆ sex    ┆ bmi  ┆ children ┆ smoker ┆ region    ┆ charges     │
│ ---  ┆ ---    ┆ ---  ┆ ---      ┆ ---    ┆ ---       ┆ ---         │
│ f64  ┆ str    ┆ f64  ┆ i64      ┆ str    ┆ str       ┆ f64         │
╞══════╪════════╪══════╪══════════╪════════╪═══════════╪═════════════╡
│ null ┆ female ┆ 27.9 ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   │
│ null ┆ male   ┆ 33.8 ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   │
│ 28.0 ┆ null   ┆ 33.0 ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    │
│ 33.0 ┆ male   ┆ 22.7 ┆ 14       ┆ no     ┆ northwest ┆ 21984.47061 │
│ 32.0 ┆ male   ┆ 28.9 ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   │
└──────┴────────┴──────┴──────────┴────────┴───────────┴─────────────┘

In [20]:
df_pl.null_count()

shape: (1, 7)
┌─────┬─────┬─────┬──────────┬────────┬────────┬─────────┐
│ age ┆ sex ┆ bmi ┆ children ┆ smoker ┆ region ┆ charges │
│ --- ┆ --- ┆ --- ┆ ---      ┆ ---    ┆ ---    ┆ ---     │
│ u32 ┆ u32 ┆ u32 ┆ u32      ┆ u32    ┆ u32    ┆ u32     │
╞═════╪═════╪═════╪══════════╪════════╪════════╪═════════╡
│ 2   ┆ 1   ┆ 0   ┆ 0        ┆ 0      ┆ 0      ┆ 0       │
└─────┴─────┴─────┴──────────┴────────┴────────┴─────────┘

In [21]:
df_pl["bmi"].drop_nulls().to_list()

[27.9,
 33.8,
 33.0,
 22.7,
 28.9,
 25.7,
 33.4,
 27.7,
 29.8,
 25.8,
 26.2,
 26.3,
 34.4,
 39.8,
 42.1,
 24.6,
 30.8,
 23.8,
 40.3,
 35.3,
 36.0,
 32.4,
 34.1,
 31.9,
 28.0,
 27.7,
 23.1,
 32.8,
 17.4,
 36.3,
 35.6,
 26.3,
 28.6,
 28.3,
 36.4,
 20.4,
 33.0,
 20.8,
 36.7,
 39.9,
 26.6,
 36.6,
 21.8,
 30.8,
 37.0,
 37.3,
 38.7,
 34.8,
 24.5,
 35.2,
 35.6,
 33.6,
 28.0,
 34.4,
 28.7,
 37.0,
 31.8,
 31.7,
 22.9,
 37.3,
 27.4,
 33.7,
 24.7,
 25.9,
 22.4,
 28.9,
 39.1,
 26.3,
 36.2,
 24.0,
 24.8,
 28.5,
 28.1,
 32.0,
 27.4,
 34.0,
 29.6,
 35.5,
 39.8,
 33.0,
 26.9,
 38.3,
 37.6,
 41.2,
 34.8,
 22.9,
 31.2,
 27.2,
 27.7,
 27.0,
 39.5,
 24.8,
 29.8,
 34.8,
 31.3,
 37.6,
 30.8,
 38.3,
 20.0,
 19.3,
 31.6,
 25.5,
 30.1,
 29.9,
 27.5,
 28.0,
 28.4,
 30.9,
 27.9,
 35.1,
 33.6,
 29.7,
 30.8,
 35.7,
 32.2,
 28.6,
 49.1,
 27.9,
 27.2,
 23.4,
 37.1,
 23.8,
 29.0,
 31.4,
 33.9,
 28.8,
 28.3,
 37.4,
 17.8,
 34.7,
 26.5,
 22.0,
 35.9,
 25.6,
 28.8,
 28.0,
 34.1,
 25.2,
 31.9,
 36.0,
 22.4,
 32.5,
 25.3,
 29.7,
 28.7,
 38.8,
 30.5,
 37.7,
 37.4,
 28.4,
 24.1,
 29.7,
 37.1,
 23.4,
 25.5,
 39.5,
 24.4,
 25.2,
 35.5,
 27.8,
 26.6,
 36.8,
 39.6,
 29.8,
 29.6,
 28.2,
 37.0,
 33.2,
 31.8,
 18.9,
 41.5,
 30.3,
 16.0,
 34.8,
 33.3,
 37.7,
 27.8,
 29.2,
 28.9,
 33.2,
 28.6,
 38.3,
 20.0,
 26.4,
 30.7,
 41.9,
 29.9,
 30.9,
 32.2,
 32.1,
 31.6,
 26.2,
 25.7,
 26.6,
 34.4,
 30.6,
 32.8,
 28.6,
 18.0,
 39.3,
 32.1,
 32.2,
 24.0,
 36.1,
 22.3,
 28.9,
 26.4,
 27.7,
 31.8,
 41.2,
 33.0,
 30.9,
 28.5,
 26.7,
 30.9,
 37.1,
 26.6,
 23.1,
 29.9,
 23.2,
 33.7,
 33.2,
 30.8,
 34.8,
 24.6,
 33.9,
 38.1,
 41.9,
 31.6,
 25.5,
 36.2,
 27.8,
 17.8,
 27.5,
 24.5,
 22.2,
 26.7,
 38.4,
 29.1,
 38.1,
 36.7,
 22.1,
 26.8,
 35.3,
 27.7,
 30.0,
 38.1,
 35.9,
 20.9,
 29.0,
 17.3,
 32.2,
 34.2,
 30.3,
 31.8,
 25.4,
 33.6,
 40.2,
 24.4,
 31.9,
 25.2,
 26.8,
 24.3,
 37.0,
 38.1,
 42.4,
 19.8,
 32.4,
 30.2,
 25.8,
 29.4,
 34.2,
 37.0,
 27.5,
 27.6,
 26.6,
 20.6,
 24.3,
 31.8,
 21.6,
 28.1,
 40.6,
 27.6,
 32.4,
 31.2,
 26.6,
 48.1,
 26.2,
 36.8,
 26.4,
 33.4,
 29.6,
 45.5,
 28.8,
 26.8,
 23.0,
 27.7,
 25.4,
 34.4,
 28.9,
 27.6,
 22.6,
 37.5,
 33.0,
 38.0,
 33.3,
 27.5,
 33.3,
 34.9,
 33.1,
 26.6,
 24.7,
 36.0,
 35.9,
 31.4,
 33.2,
 32.2,
 32.8,
 27.6,
 37.3,
 25.3,
 29.6,
 30.8,
 40.9,
 27.2,
 34.1,
 23.2,
 36.5,
 33.8,
 36.7,
 36.4,
 27.4,
 31.2,
 28.8,
 35.7,
 34.5,
 25.7,
 27.6,
 32.3,
 27.7,
 27.6,
 30.0,
 27.6,
 36.8,
 41.5,
 29.3,
 35.8,
 33.3,
 29.9,
 27.8,
 23.2,
 25.6,
 27.7,
 35.2,
 38.3,
 27.6,
 43.9,
 29.8,
 41.9,
 20.8,
 32.3,
 30.5,
 21.7,
 26.4,
 21.9,
 30.8,
 32.3,
 25.0,
 32.0,
 30.4,
 21.1,
 22.2,
 33.2,
 32.9,
 33.3,
 28.3,
 24.9,
 40.2,
 30.1,
 31.5,
 18.0,
 30.7,
 33.0,
 43.3,
 22.1,
 34.4,
 39.0,
 25.4,
 22.6,
 30.2,
 35.6,
 37.4,
 31.4,
 31.4,
 32.3,
 19.9,
 34.4,
 31.0,
 25.6,
 38.2,
 20.6,
 47.5,
 33.0,
 32.3,
 20.4,
 38.4,
 24.3,
 23.6,
 21.1,
 30.0,
 17.5,
 20.2,
 17.2,
 23.9,
 35.2,
 35.6,
 34.1,
 22.6,
 39.2,
 27.0,
 33.9,
 35.9,
 32.8,
 30.6,
 30.2,
 24.3,
 27.3,
 29.2,
 16.8,
 30.4,
 33.1,
 20.2,
 26.9,
 30.5,
 28.6,
 33.1,
 31.7,
 28.9,
 46.8,
 29.4,
 32.7,
 33.5,
 43.0,
 36.5,
 26.7,
 33.1,
 29.6,
 25.6,
 29.6,
 38.6,
 29.6,
 24.1,
 23.4,
 29.7,
 46.5,
 37.4,
 30.1,
 30.5,
 39.6,
 33.0,
 36.6,
 30.0,
 38.1,
 25.9,
 25.2,
 28.4,
 28.7,
 33.8,
 24.3,
 24.1,
 32.7,
 30.1,
 29.8,
 33.3,
 25.1,
 28.3,
 28.5,
 35.6,
 36.8,
 32.6,
 41.3,
 37.5,
 31.4,
 39.5,
 34.3,
 31.1,
 21.5,
 28.7,
 38.1,
 31.2,
 32.9,
 25.1,
 25.1,
 43.4,
 25.7,
 27.9,
 23.6,
 28.7,
 24.0,
 39.2,
 34.4,
 26.0,
 23.2,
 30.2,
 28.9,
 30.9,
 31.4,
 23.8,
 25.3,
 28.7,
 32.1,
 33.7,
 22.4,
 30.4,
 28.3,
 35.7,
 35.3,
 30.5,
 31.0,
 30.9,
 27.4,
 44.2,
 33.9,
 37.7,
 26.1,
 33.9,
 30.6,
 25.8,
 39.4,
 25.5,
 42.1,
 31.7,
 29.7,
 36.2,
 40.5,
 28.0,
 38.9,
 30.2,
 28.0,
 31.4,
 38.0,
 31.8,
 36.3,
 47.4,
 30.2,
 25.8,
 35.4,
 46.7,
 28.6,
 46.2,
 30.8,
 28.9,
 21.4,
 31.7,
 41.3,
 23.8,
 33.4,
 34.2,
 34.1,
 35.5,
 20.0,
 32.7,
 30.5,
 44.8,
 32.1,
 30.5,
 40.6,
 30.6,
 31.9,
 40.6,
 29.1,
 37.3,
 43.1,
 36.9,
 34.3,
 27.2,
 26.8,
 38.1,
 30.2,
 23.5,
 25.5,
 30.6,
 45.4,
 23.6,
 20.7,
 28.3,
 20.2,
 30.2,
 35.9,
 30.7,
 29.0,
 19.6,
 31.1,
 21.8,
 40.3,
 33.7,
 29.5,
 33.2,
 32.6,
 37.5,
 39.2,
 31.6,
 25.3,
 39.0,
 28.3,
 34.1,
 25.2,
 23.7,
 27.0,
 37.8,
 29.4,
 34.8,
 33.2,
 19.0,
 33.0,
 36.6,
 28.6,
 25.6,
 33.1,
 37.1,
 31.4,
 34.1,
 21.3,
 33.5,
 28.8,
 26.0,
 28.9,
 42.5,
 38.0,
 39.0,
 36.1,
 29.3,
 35.5,
 22.7,
 39.7,
 38.2,
 24.5,
 38.1,
 26.4,
 33.7,
 42.4,
 28.3,
 33.9,
 35.0,
 35.3,
 30.8,
 26.2,
 23.4,
 28.5,
 33.0,
 42.7,
 39.6,
 31.1,
 36.3,
 35.2,
 25.3,
 42.4,
 33.2,
 35.9,
 28.8,
 46.5,
 24.0,
 31.5,
 33.7,
 23.0,
 38.1,
 28.7,
 32.8,
 32.0,
 29.8,
 31.6,
 31.2,
 29.7,
 31.0,
 43.9,
 21.4,
 40.8,
 31.4,
 36.1,
 23.2,
 17.4,
 20.3,
 35.3,
 24.3,
 18.5,
 26.4,
 26.1,
 41.7,
 24.1,
 31.1,
 27.4,
 36.2,
 32.4,
 23.7,
 34.8,
 40.2,
 32.3,
 35.8,
 33.7,
 39.3,
 34.9,
 44.7,
 41.5,
 26.4,
 29.5,
 32.9,
 38.1,
 28.7,
 30.5,
 27.7,
 35.2,
 23.5,
 30.7,
 40.5,
 22.6,
 28.9,
 22.6,
 24.3,
 36.7,
 33.4,
 40.7,
 36.6,
 37.4,
 35.4,
 27.1,
 39.0,
 28.4,
 21.8,
 40.3,
 36.1,
 24.4,
 21.4,
 30.1,
 27.3,
 32.1,
 34.8,
 38.4,
 23.7,
 31.7,
 35.5,
 24.0,
 29.2,
 34.1,
 26.6,
 26.4,
 30.1,
 27.0,
 21.8,
 36.0,
 30.9,
 26.4,
 29.0,
 37.9,
 22.8,
 33.6,
 27.6,
 22.8,
 27.8,
 37.4,
 38.2,
 34.6,
 35.2,
 27.1,
 26.0,
 25.2,
 31.8,
 32.3,
 29.0,
 39.7,
 19.5,
 36.1,
 26.7,
 36.5,
 28.9,
 34.2,
 33.3,
 32.3,
 39.8,
 34.3,
 28.9,
 24.4,
 41.1,
 36.0,
 27.6,
 29.3,
 27.7,
 37.0,
 36.9,
 22.5,
 29.9,
 41.8,
 27.6,
 23.2,
 20.9,
 31.9,
 28.5,
 44.2,
 22.9,
 33.1,
 24.8,
 26.2,
 36.0,
 22.3,
 42.2,
 26.5,
 35.8,
 41.4,
 36.6,
 30.1,
 25.8,
 30.8,
 42.9,
 21.0,
 22.5,
 34.4,
 31.5,
 24.2,
 37.1,
 26.1,
 35.5,
 33.7,
 17.7,
 31.1,
 29.8,
 24.3,
 31.8,
 31.8,
 28.0,
 30.8,
 21.8,
 33.1,
 25.8,
 23.8,
 34.4,
 33.8,
 36.0,
 31.5,
 28.3,
 23.5,
 31.4,
 31.1,
 24.7,
 32.8,
 29.8,
 30.5,
 32.4,
 34.2,
 50.4,
 24.1,
 32.8,
 30.8,
 32.3,
 35.5,
 23.8,
 23.8,
 29.6,
 33.1,
 24.1,
 32.2,
 28.1,
 47.6,
 28.0,
 33.5,
 19.9,
 25.4,
 29.9,
 37.3,
 43.7,
 23.7,
 24.3,
 36.2,
 29.5,
 24.9,
 30.1,
 21.8,
 28.1,
 27.1,
 33.4,
 28.8,
 29.5,
 34.8,
 27.4,
 22.1,
 37.0,
 26.7,
 28.9,
 29.0,
 30.0,
 39.5,
 33.6,
 26.9,
 29.0,
 24.0,
 38.9,
 32.1,
 44.0,
 20.0,
 25.6,
 40.3,
 22.5,
 22.5,
 40.9,
 27.3,
 36.8,
 35.1,
 29.4,
 32.6,
 32.3,
 39.8,
 24.6,
 28.3,
 31.7,
 26.7,
 27.5,
 24.6,
 34.0,
 26.9,
 22.9,
 28.2,
 34.2,
 25.0,
 33.2,
 31.0,
 35.8,
 23.2,
 32.1,
 23.4,
 20.1,
 39.2,
 34.2,
 46.5,
 32.5,
 25.8,
 35.3,
 37.2,
 27.5,
 29.7,
 24.2,
 26.2,
 29.5,
 23.2,
 46.1,
 40.2,
 22.6,
 39.9,
 35.8,
 35.8,
 34.2,
 31.3,
 29.7,
 18.3,
 42.9,
 28.4,
 30.2,
 27.8,
 39.5,
 30.8,
 26.8,
 35.0,
 36.7,
 39.6,
 25.9,
 35.2,
 24.8,
 36.8,
 27.1,
 24.8,
 25.4,
 25.7,
 34.3,
 28.2,
 23.6,
 20.2,
 40.5,
 35.4,
 22.9,
 40.2,
 29.2,
 40.0,
 29.9,
 25.5,
 21.4,
 25.9,
 30.6,
 30.1,
 25.8,
 30.1,
 27.6,
 34.7,
 20.5,
 19.8,
 27.8,
 31.6,
 28.3,
 20.0,
 23.3,
 34.1,
 36.8,
 36.3,
 26.9,
 ...]

In [22]:
nrow = df_pl.height

In [23]:
col_names = df_pl.columns

In [24]:
col_names

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [25]:
df_dtypes = [str(df_pl[name].dtype) for name in col_names]

In [26]:
df_dtypes

['Float64', 'String', 'Float64', 'Int64', 'String', 'String', 'Float64']

In [27]:
for i,dtype in enumerate(df_dtypes):
    if dtype in ["String", "Categorical", "Categories", "Enum", "Utf8"]:
        print(i,dtype)

1 String
4 String
5 String

In [28]:
df_pl[:,1].unique().to_list()

[None, 'male', 'female']

In [29]:
categorical_encode_maps = {}

for i,dtype in enumerate(df_dtypes):
    if dtype in ["String", "Categorical", "Categories", "Enum", "Utf8"]:
        print(i,col_names[i],df_pl[:,i].unique().to_list())

        unique_vals = df_pl[:, i].unique().to_list()
        col = col_names[i]

        if len(unique_vals) > nrow/3:
            Warning(f"Check {col} does not contain open ended values. This implementation only process categorical levels...")

        map_name = col + "_map"

        categorical_encode_maps[map_name] = {
            val: idx for idx, val in enumerate(unique_vals)
        }

1 sex [None, 'female', 'male']
4 smoker ['yes', 'no']
5 region ['northwest', 'southwest', 'northeast', 'southeast']

In [30]:
categorical_encode_maps

{'sex_map': {'male': 0, 'female': 1, None: 2},
 'smoker_map': {'yes': 0, 'no': 1},
 'region_map': {'northwest': 0,
  'southeast': 1,
  'southwest': 2,
  'northeast': 3}}

In [31]:
len(categorical_encode_maps)

3

In [32]:
categorical_decode_maps = {
    outer_key: {v: k for k, v in inner_dict.items()}
    for outer_key, inner_dict in categorical_encode_maps.items()
}

In [33]:
categorical_decode_maps

{'sex_map': {0: 'male', 1: 'female', 2: None},
 'smoker_map': {0: 'yes', 1: 'no'},
 'region_map': {0: 'northwest',
  1: 'southeast',
  2: 'southwest',
  3: 'northeast'}}

In [34]:
insurance_data["bmi"]

0       27.9
1       33.8
2       33.0
3       22.7
4       28.9
        ...
1333    31.0
1334    31.9
1335    36.8
1336    25.8
1337    29.1
Name: bmi, Length: 1338, dtype: float64

In [35]:
import importlib
import src.utils.tabular_datasets as tabular_datasets
importlib.reload(tabular_datasets)
from src.utils.tabular_datasets import ArgnDataset

In [100]:
insurance_data

       age     sex   bmi  children smoker     region      charges
0      NaN  female  27.9         0    yes  southwest  16884.92400
1      NaN    male  33.8         1     no  southeast   1725.55230
2     28.0    None  33.0         3     no  southeast   4449.46200
3     33.0    male  22.7        14     no  northwest  21984.47061
4     32.0    male  28.9         0     no  northwest   3866.85520
...    ...     ...   ...       ...    ...        ...          ...
1333  50.0    male  31.0         3     no  northwest  10600.54830
1334  18.0  female  31.9         0     no  northeast   2205.98080
1335  18.0  female  36.8         0     no  southeast   1629.83350
1336  21.0  female  25.8         0     no  southwest   2007.94500
1337  61.0  female  29.1         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [36]:
insurance_table_test = ArgnDataset(insurance_data, clip_cols = True)

In [37]:
dir(insurance_table_test)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_bool_columns',
 '_categorical_columns',
 '_column_binned_designs',
 '_datetime_columns',
 '_float_columns_to_cast_to_integer',
 '_incompatible_columns',
 '_is_protocol',
 '_is_runtime_protocol',
 '_numeric_strategy',
 '_numerical_binned_columns',
 '_numerical_digit_columns',
 '_numerical_discrete_columns',
 '_numerical_float_columns',
 '_raw_data',
 '_table',
 '_table_pd',
 'argn_preprocessing',
 'categorical_decoding_maps',
 'categorical_encoding_maps',
 'clip_cols',
 'col_names',
 'dtypes',
 'load_data',
 'ncol',
 'nrow',
 'numerical_binned_decoding_maps',
 'numerical_binned_encoding_maps',
 'numerical_discrete_decoding_maps',
 'numerical_discrete_encoding_maps',
 'table',
 'table_dim']

In [38]:
insurance_data.head(10)

    age     sex   bmi  children smoker     region      charges
0   NaN  female  27.9         0    yes  southwest  16884.92400
1   NaN    male  33.8         1     no  southeast   1725.55230
2  28.0    None  33.0         3     no  southeast   4449.46200
3  33.0    male  22.7        14     no  northwest  21984.47061
4  32.0    male  28.9         0     no  northwest   3866.85520
5  31.0  female  25.7         0     no  southeast   3756.62160
6  46.0  female  33.4         1     no  southeast   8240.58960
7  37.0  female  27.7         3     no  northwest   7281.50560
8  37.0    male  29.8         2     no  northeast   6406.41070
9  60.0  female  25.8         0     no  northwest  28923.13692

In [39]:
insurance_table_test.table.head(10)

   age  sex  bmi  children  smoker  region      charges
0    0    2   35         0       1       2  16884.92400
1    0    0   71         1       0       3   1725.55230
2   11    1   66         3       0       3   4449.46200
3   16    0   10         5       0       1  21984.47061
4   15    0   42         0       0       1   3866.85520
5   14    2   23         0       0       3   3756.62160
6   29    2   69         1       0       3   8240.58960
7   20    2   34         3       0       1   7281.50560
8   20    0   47         2       0       0   6406.41070
9   43    2   24         0       0       1  28923.13692

In [40]:
insurance_table_test._categorical_columns

[('sex', 1), ('smoker', 4), ('region', 5)]

In [41]:
c,i = zip(*insurance_table_test._categorical_columns)
print(c)
print(i)

('sex', 'smoker', 'region')
(1, 4, 5)

In [42]:
insurance_table_test._float_columns_to_cast_to_integer

[('age', 0)]

In [43]:
insurance_table_test._table

shape: (1_338, 7)
┌─────┬─────┬─────┬──────────┬────────┬────────┬─────────────┐
│ age ┆ sex ┆ bmi ┆ children ┆ smoker ┆ region ┆ charges     │
│ --- ┆ --- ┆ --- ┆ ---      ┆ ---    ┆ ---    ┆ ---         │
│ i64 ┆ i64 ┆ i64 ┆ i64      ┆ i64    ┆ i64    ┆ f64         │
╞═════╪═════╪═════╪══════════╪════════╪════════╪═════════════╡
│ 0   ┆ 2   ┆ 35  ┆ 0        ┆ 1      ┆ 2      ┆ 16884.924   │
│ 0   ┆ 0   ┆ 71  ┆ 1        ┆ 0      ┆ 3      ┆ 1725.5523   │
│ 11  ┆ 1   ┆ 66  ┆ 3        ┆ 0      ┆ 3      ┆ 4449.462    │
│ 16  ┆ 0   ┆ 10  ┆ 5        ┆ 0      ┆ 1      ┆ 21984.47061 │
│ 15  ┆ 0   ┆ 42  ┆ 0        ┆ 0      ┆ 1      ┆ 3866.8552   │
│ …   ┆ …   ┆ …   ┆ …        ┆ …      ┆ …      ┆ …           │
│ 33  ┆ 0   ┆ 55  ┆ 3        ┆ 0      ┆ 1      ┆ 10600.5483  │
│ 1   ┆ 2   ┆ 60  ┆ 0        ┆ 0      ┆ 0      ┆ 2205.9808   │
│ 1   ┆ 2   ┆ 85  ┆ 0        ┆ 0      ┆ 3      ┆ 1629.8335   │
│ 4   ┆ 2   ┆ 24  ┆ 0        ┆ 0      ┆ 2      ┆ 2007.945    │
│ 44  ┆ 2   ┆ 43  ┆ 0        ┆ 1      ┆ 1      ┆ 29141.3603  │
└─────┴─────┴─────┴──────────┴────────┴────────┴─────────────┘

In [44]:
insurance_table_test.numerical_discrete_encoding_maps

{'age': {None: 0,
  18: 1,
  19: 2,
  20: 3,
  21: 4,
  22: 5,
  23: 6,
  24: 7,
  25: 8,
  26: 9,
  27: 10,
  28: 11,
  29: 12,
  30: 13,
  31: 14,
  32: 15,
  33: 16,
  34: 17,
  35: 18,
  36: 19,
  37: 20,
  38: 21,
  39: 22,
  40: 23,
  41: 24,
  42: 25,
  43: 26,
  44: 27,
  45: 28,
  46: 29,
  47: 30,
  48: 31,
  49: 32,
  50: 33,
  51: 34,
  52: 35,
  53: 36,
  54: 37,
  55: 38,
  56: 39,
  57: 40,
  58: 41,
  59: 42,
  60: 43,
  61: 44,
  62: 45,
  63: 46,
  64: 47},
 'children': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}}

In [45]:
insurance_table_test._incompatible_columns

[]

In [46]:
columns_with_float, _ = zip(*insurance_table_test._numerical_float_columns)

In [47]:
small_numbers = insurance_table_test._table['bmi'].to_numpy()
big_bumbers = insurance_table_test._table['charges'].to_numpy()

In [48]:
insurance_table_test._numeric_strategy

{'bmi': 'BINNED', 'charges': 'DIGIT'}

In [49]:
insurance_table_test._numerical_float_columns

[('bmi', 2), ('charges', 6)]

In [50]:
lower = np.quantile(small_numbers, 0.01)
upper = np.quantile(small_numbers, 0.99)

print(f"lower = {lower} - upper = {upper}")

clipped = np.clip(small_numbers, lower, upper)

np.sort(small_numbers[np.logical_not(small_numbers == clipped)])

lower = 1.370000000000001 - upper = 99.62999999999988

array([  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         1, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [51]:
def clip_columns(df_pl: pl.DataFrame, cols_to_process: list[tuple[str,int]], lower_quantile: float = 0.01, upper_quantile: float = 0.99) -> pl.DataFrame:
    """
    Clips columns with numeical values.

    Parameters:
    ----------

    df_pl: pl.DataFrame
        A polars data aframe
    cols_to_process: list[tuple[str,int]]
        Lis of columns with either integer or float values to beclipped
    lower_quantile: int, default_value = 0.01
        Lower quantile threshold. Values below this quantile are replaced 
        with the value at this quantile. 
        Setting the lower cutoff at 0.01 selects the value below
        which the lowest 1% of data points fall
    upper_quantile: int, default_value = 0.99
        Upper quantile threshold. Values above this quantile are replaced 
        with the value at this quantile.
        Setting the upper cutoff at 0.99 selects the value below
        which the lowest 99% of data points fall. It also means selecting
        a value above which the highest 1% of data points fall.

    Returns:
    -------

    processed_df : pl.DataFrame
        Polars data frame with specified columns clipped to the given quantile range
    """

    processed_df = df_pl
    cols_to_process_names, _ = zip(*cols_to_process)

    for col_name in cols_to_process_names:
        col_values = df_pl[col_name].to_numpy()
        lower = np.quantile(col_values, 0.01)
        upper = np.quantile(col_values, 0.99)
        processed_df.with_columns(pl.col("a").clip(lower, upper))

    return processed_df

In [52]:
test_clipping_df1 = pl.DataFrame({"a": [-50, 5, 50, None], "b": [150.92, 3, 12, 123]})
print(test_clipping_df1)

shape: (4, 2)
┌──────┬────────┐
│ a    ┆ b      │
│ ---  ┆ ---    │
│ i64  ┆ f64    │
╞══════╪════════╡
│ -50  ┆ 150.92 │
│ 5    ┆ 3.0    │
│ 50   ┆ 12.0   │
│ null ┆ 123.0  │
└──────┴────────┘

In [53]:
test_clipping_df2 =test_clipping_df1.with_columns(pl.col("a").clip(1, 10))
print(test_clipping_df2)

shape: (4, 2)
┌──────┬────────┐
│ a    ┆ b      │
│ ---  ┆ ---    │
│ i64  ┆ f64    │
╞══════╪════════╡
│ 1    ┆ 150.92 │
│ 5    ┆ 3.0    │
│ 10   ┆ 12.0   │
│ null ┆ 123.0  │
└──────┴────────┘

In [54]:
import warnings

In [55]:
from src.utils.argn_encoder_decoder import BinDesign

In [56]:
one_col = BinDesign(1,[2,3])
another_col = BinDesign(2,[4,5,6])
test_bin_mapping_list = [one_col, another_col]
test_bin_mapping_dict = {"one_col_key" : BinDesign(1,[2,3]), "another_col_key" : BinDesign(2,[4,5,6])}

In [57]:
test_bin_mapping_list[0].n_bins

1

In [58]:
test_bin_mapping_dict["one_col_key"].n_bins

1

In [59]:
def get_bin_designs(df_pl: pl.DataFrame, float_cols: list[tuple[str,int]]) -> dict[str,BinDesign]:
    """
    Assumes a polars data frame and calculates the number of bins and the corresponding edges  
    required for BINNED encoding for each column in float_cols. Returns this design as a dict. 

    Parameters:
    ----------

    df_pl : pl.DataFrame
        A polars data frame 
    float_cols : list[tuple[str,int]]
        A list of (column_name, column_index) pairs. The columns
        are a subset of the existing columns in df_pl 

    Returns:
    -------

    columns_bin_designs : dict[str,BinDesign]
        A dictionary with column name as key and a BinDesign 
        as a corresponding value. BinDesign is a container for
        the number of bins and the edges for a given column
    """

    if len(float_cols) == 0:
        warnings.warn("get_n_bins() received an empty list as an argument...")
        return {}

    MAX_BINS = 100

    cols_to_process_names, _ = zip(*float_cols)

    columns_bin_designs = {}
    
    for col_name in cols_to_process_names:
        n_unique_vals = len(df_pl[col_name].unique().to_list())
        n_bins = min(MAX_BINS, n_unique_vals)
        percentiles = np.linspace(0, 100, n_bins + 1)
        edges = np.percentile(df_pl[col].drop_nulls().to_numpy(), percentiles) # .drop_nulls() to avoid TypeError due to propagation of nulls
        
        unique_edges = np.unique(edges)  # remove duplicates from highly skewed data
        edges_diff = len(edges) - len(unique_edges)
        if edges_diff > 0:
            edges = unique_edges
            n_bins = n_bins - edges_diff

        columns_bin_designs[col_name] = BinDesign(n_bins, edges)
    
    return columns_bin_designs

In [60]:
n_unq_vl = len(list(np.unique(small_numbers)))
n_bn = min(100,n_unq_vl)

In [61]:
np.quantile(small_numbers, np.linspace(0, 1, n_bn + 1))

array([  1.  ,   1.37,   2.74,   4.  ,   5.  ,   5.85,   7.  ,   7.59,
         9.  ,  10.  ,  11.  ,  12.  ,  13.  ,  13.81,  15.  ,  15.55,
        17.  ,  18.  ,  19.  ,  20.  ,  20.4 ,  21.77,  23.  ,  24.  ,
        25.  ,  26.  ,  27.  ,  27.99,  29.  ,  30.  ,  31.  ,  32.  ,
        33.  ,  34.  ,  35.  ,  36.  ,  37.  ,  38.  ,  39.  ,  39.43,
        41.  ,  42.  ,  43.  ,  44.  ,  45.  ,  46.  ,  47.  ,  48.  ,
        49.  ,  50.  ,  51.  ,  52.  ,  53.  ,  54.  ,  55.  ,  55.35,
        57.  ,  58.  ,  59.  ,  60.  ,  60.2 ,  62.  ,  63.  ,  64.  ,
        65.  ,  66.  ,  67.  ,  68.  ,  69.  ,  70.  ,  71.  ,  72.  ,
        73.  ,  74.  ,  75.  ,  76.  ,  77.  ,  78.  ,  78.86,  80.  ,
        81.  ,  82.  ,  83.  ,  84.  ,  85.  ,  86.  ,  87.  ,  87.19,
        89.  ,  90.  ,  90.3 ,  91.67,  92.04,  93.41,  94.78,  96.  ,
        97.  ,  97.89,  98.26,  99.63, 100.  ])

In [62]:
percentiles = np.linspace(0, 100, n_bn + 1)  # n_bins+1 edges for n_bins intervals
edges = np.percentile(small_numbers, percentiles) # add .dropna()
edges

array([  1.  ,   1.37,   2.74,   4.  ,   5.  ,   5.85,   7.  ,   7.59,
         9.  ,  10.  ,  11.  ,  12.  ,  13.  ,  13.81,  15.  ,  15.55,
        17.  ,  18.  ,  19.  ,  20.  ,  20.4 ,  21.77,  23.  ,  24.  ,
        25.  ,  26.  ,  27.  ,  27.99,  29.  ,  30.  ,  31.  ,  32.  ,
        33.  ,  34.  ,  35.  ,  36.  ,  37.  ,  38.  ,  39.  ,  39.43,
        41.  ,  42.  ,  43.  ,  44.  ,  45.  ,  46.  ,  47.  ,  48.  ,
        49.  ,  50.  ,  51.  ,  52.  ,  53.  ,  54.  ,  55.  ,  55.35,
        57.  ,  58.  ,  59.  ,  60.  ,  60.2 ,  62.  ,  63.  ,  64.  ,
        65.  ,  66.  ,  67.  ,  68.  ,  69.  ,  70.  ,  71.  ,  72.  ,
        73.  ,  74.  ,  75.  ,  76.  ,  77.  ,  78.  ,  78.86,  80.  ,
        81.  ,  82.  ,  83.  ,  84.  ,  85.  ,  86.  ,  87.  ,  87.19,
        89.  ,  90.  ,  90.3 ,  91.67,  92.04,  93.41,  94.78,  96.  ,
        97.  ,  97.89,  98.26,  99.63, 100.  ])

In [63]:
edges = np.unique(edges)  # remove duplicates from highly skewed data
edges

array([  1.  ,   1.37,   2.74,   4.  ,   5.  ,   5.85,   7.  ,   7.59,
         9.  ,  10.  ,  11.  ,  12.  ,  13.  ,  13.81,  15.  ,  15.55,
        17.  ,  18.  ,  19.  ,  20.  ,  20.4 ,  21.77,  23.  ,  24.  ,
        25.  ,  26.  ,  27.  ,  27.99,  29.  ,  30.  ,  31.  ,  32.  ,
        33.  ,  34.  ,  35.  ,  36.  ,  37.  ,  38.  ,  39.  ,  39.43,
        41.  ,  42.  ,  43.  ,  44.  ,  45.  ,  46.  ,  47.  ,  48.  ,
        49.  ,  50.  ,  51.  ,  52.  ,  53.  ,  54.  ,  55.  ,  55.35,
        57.  ,  58.  ,  59.  ,  60.  ,  60.2 ,  62.  ,  63.  ,  64.  ,
        65.  ,  66.  ,  67.  ,  68.  ,  69.  ,  70.  ,  71.  ,  72.  ,
        73.  ,  74.  ,  75.  ,  76.  ,  77.  ,  78.  ,  78.86,  80.  ,
        81.  ,  82.  ,  83.  ,  84.  ,  85.  ,  86.  ,  87.  ,  87.19,
        89.  ,  90.  ,  90.3 ,  91.67,  92.04,  93.41,  94.78,  96.  ,
        97.  ,  97.89,  98.26,  99.63, 100.  ])

In [64]:
def select_numeric_strategy(df_pl: pl.DataFrame, float_cols: list[tuple[str,int]]) -> list[str]:

    col_encoding_strategy = []

    for col in float_cols:

        numbers_to_analyze = df_pl[col].to_list()
        string_numbers = [str(abs(number)) for number in numbers_to_analyze] 
        splited_numbers = [tuple(str_number.split('.')) for str_number in string_numbers]
        len_int_and_dec = [(len(x), len(y)) for x, y in splited_numbers]
        
        max_decimal_places = max(x[1] for x in len_int_and_dec)

        max_num_digits = max((x[0]+x[1]) for x in len_int_and_dec)

        if max_decimal_places <=2:
            col_encoding_strategy.append("BINNED")
        elif max_num_digits > 6 or max_decimal_places > 3:
            col_encoding_strategy.append("DIGIT")
        else:
            col_encoding_strategy.append("BINNED")

    return col_encoding_strategy

In [65]:
columns_with_float

('bmi', 'charges')

In [66]:
# Numeric discrete

def generate_numeric_discrete_encoding_mappings():
    
    numerical_discrete_encoding_maps = {}
    numerical_discrete_columns = []

    for i,dtype in enumerate(df_dtypes):
        if dtype in ["Int8", "Int16", "Int32", "Int64", "UInt8", "UInt16", "UInt32", "UInt64"]:

            unique_vals = df_pl[:, i].unique().to_list()
            col = col_names[i]

In [67]:
# Numeric Binned

In [68]:
insurance_table_test._numeric_strategy

{'bmi': 'BINNED', 'charges': 'DIGIT'}

In [69]:
insurance_table_test._numeric_strategy.values()

dict_values(['BINNED', 'DIGIT'])

In [70]:
insurance_table_test._numeric_strategy

{'bmi': 'BINNED', 'charges': 'DIGIT'}

In [71]:
binned_strategy_target_cols = [col_name for col_name, strategy in insurance_table_test._numeric_strategy.items() if strategy == "BINNED"]
digit_strategy_target_cols = [col_name for col_name, strategy in insurance_table_test._numeric_strategy.items() if strategy == "DIGIT"]

In [72]:
binned_strategy_target_cols

['bmi']

In [73]:
_numerical_binned_columns = [(col_name, col_index) for col_name, col_index in insurance_table_test._numerical_float_columns if col_name in binned_strategy_target_cols]
_numerical_digit_columns = [(col_name, col_index) for col_name, col_index in insurance_table_test._numerical_float_columns if col_name in digit_strategy_target_cols]

In [74]:
_numerical_digit_columns

[('charges', 6)]

In [75]:
insurance_table_test._numerical_float_columns

[('bmi', 2), ('charges', 6)]

In [76]:
type(insurance_table_test._column_binned_designs)

dict

In [77]:
insurance_table_test._column_binned_designs["bmi"].edges

array([17.937  , 17.96031, 19.274  , 20.     , 20.5    , 21.27   ,
       21.7    , 21.859  , 22.3    , 22.6    , 23.     , 23.2    ,
       23.5    , 23.781  , 24.     , 24.255  , 24.4    , 24.6    ,
       24.9    , 25.2    , 25.34   , 25.577  , 25.7    , 25.8    ,
       26.     , 26.3    , 26.4    , 26.699  , 26.8    , 27.1    ,
       27.4    , 27.5    , 27.6    , 27.7    , 27.8    , 28.     ,
       28.1    , 28.3    , 28.5    , 28.643  , 28.8    , 28.9    ,
       29.1    , 29.4    , 29.6    , 29.7    , 29.8    , 29.9    ,
       30.1    , 30.2    , 30.4    , 30.5    , 30.7    , 30.8    ,
       31.     , 31.135  , 31.4    , 31.5    , 31.7    , 31.8    ,
       32.02   , 32.2    , 32.3    , 32.5    , 32.7    , 32.9    ,
       33.1    , 33.2    , 33.3    , 33.5    , 33.7    , 33.9    ,
       34.1    , 34.2    , 34.4    , 34.7    , 34.9    , 35.2    ,
       35.486  , 35.7    , 35.9    , 36.1    , 36.3    , 36.6    ,
       36.8    , 37.     , 37.2    , 37.419  , 38.     , 38.2    ,
       38.63   , 39.167  , 39.504  , 39.841  , 40.378  , 41.1    ,
       41.8    , 42.489  , 43.926  , 46.31907, 46.389  ])

In [78]:
for i in range(insurance_table_test._column_binned_designs["bmi"].n_bins):
    print(i, " >> ", insurance_table_test._column_binned_designs["bmi"].edges[i], " - ", insurance_table_test._column_binned_designs["bmi"].edges[i+1])

0  >>  17.936999999999998  -  17.96031
1  >>  17.96031  -  19.274
2  >>  19.274  -  20.0
3  >>  20.0  -  20.5
4  >>  20.5  -  21.270000000000003
5  >>  21.270000000000003  -  21.7
6  >>  21.7  -  21.858999999999998
7  >>  21.858999999999998  -  22.3
8  >>  22.3  -  22.6
9  >>  22.6  -  23.0
10  >>  23.0  -  23.2
11  >>  23.2  -  23.5
12  >>  23.5  -  23.781000000000002
13  >>  23.781000000000002  -  24.0
14  >>  24.0  -  24.255
15  >>  24.255  -  24.4
16  >>  24.4  -  24.6
17  >>  24.6  -  24.9
18  >>  24.9  -  25.2
19  >>  25.2  -  25.340000000000003
20  >>  25.340000000000003  -  25.576999999999998
21  >>  25.576999999999998  -  25.7
22  >>  25.7  -  25.8
23  >>  25.8  -  26.0
24  >>  26.0  -  26.3
25  >>  26.3  -  26.4
26  >>  26.4  -  26.699
27  >>  26.699  -  26.8
28  >>  26.8  -  27.1
29  >>  27.1  -  27.4
30  >>  27.4  -  27.5
31  >>  27.5  -  27.6
32  >>  27.6  -  27.7
33  >>  27.7  -  27.8
34  >>  27.8  -  28.0
35  >>  28.0  -  28.1
36  >>  28.1  -  28.3
37  >>  28.3  -  28.5
38  >>  28.5  -  28.643000000000008
39  >>  28.643000000000008  -  28.8
40  >>  28.8  -  28.9
41  >>  28.9  -  29.1
42  >>  29.1  -  29.4
43  >>  29.4  -  29.6
44  >>  29.6  -  29.7
45  >>  29.7  -  29.8
46  >>  29.8  -  29.9
47  >>  29.9  -  30.1
48  >>  30.1  -  30.2
49  >>  30.2  -  30.4
50  >>  30.4  -  30.5
51  >>  30.5  -  30.7
52  >>  30.7  -  30.8
53  >>  30.8  -  31.0
54  >>  31.0  -  31.135
55  >>  31.135  -  31.4
56  >>  31.4  -  31.5
57  >>  31.5  -  31.7
58  >>  31.7  -  31.8
59  >>  31.8  -  32.019999999999996
60  >>  32.019999999999996  -  32.2
61  >>  32.2  -  32.3
62  >>  32.3  -  32.5
63  >>  32.5  -  32.7
64  >>  32.7  -  32.9
65  >>  32.9  -  33.1
66  >>  33.1  -  33.2
67  >>  33.2  -  33.3
68  >>  33.3  -  33.5
69  >>  33.5  -  33.7
70  >>  33.7  -  33.9
71  >>  33.9  -  34.1
72  >>  34.1  -  34.2
73  >>  34.2  -  34.4
74  >>  34.4  -  34.7
75  >>  34.7  -  34.9
76  >>  34.9  -  35.2
77  >>  35.2  -  35.48600000000001
78  >>  35.48600000000001  -  35.7
79  >>  35.7  -  35.9
80  >>  35.9  -  36.1
81  >>  36.1  -  36.3
82  >>  36.3  -  36.6
83  >>  36.6  -  36.8
84  >>  36.8  -  37.0
85  >>  37.0  -  37.2
86  >>  37.2  -  37.419000000000004
87  >>  37.419000000000004  -  38.0
88  >>  38.0  -  38.2
89  >>  38.2  -  38.629999999999995
90  >>  38.629999999999995  -  39.16700000000001
91  >>  39.16700000000001  -  39.504
92  >>  39.504  -  39.84100000000001
93  >>  39.84100000000001  -  40.37799999999999
94  >>  40.37799999999999  -  41.1
95  >>  41.1  -  41.8
96  >>  41.8  -  42.48899999999999
97  >>  42.48899999999999  -  43.925999999999995
98  >>  43.925999999999995  -  46.31906999999996
99  >>  46.31906999999996  -  46.38899999999997

In [79]:
import logging

In [80]:
insurance_table_test._column_binned_designs

{'bmi': BinDesign(n_bins=100, edges=array([17.937  , 17.96031, 19.274  , 20.     , 20.5    , 21.27   ,
        21.7    , 21.859  , 22.3    , 22.6    , 23.     , 23.2    ,
        23.5    , 23.781  , 24.     , 24.255  , 24.4    , 24.6    ,
        24.9    , 25.2    , 25.34   , 25.577  , 25.7    , 25.8    ,
        26.     , 26.3    , 26.4    , 26.699  , 26.8    , 27.1    ,
        27.4    , 27.5    , 27.6    , 27.7    , 27.8    , 28.     ,
        28.1    , 28.3    , 28.5    , 28.643  , 28.8    , 28.9    ,
        29.1    , 29.4    , 29.6    , 29.7    , 29.8    , 29.9    ,
        30.1    , 30.2    , 30.4    , 30.5    , 30.7    , 30.8    ,
        31.     , 31.135  , 31.4    , 31.5    , 31.7    , 31.8    ,
        32.02   , 32.2    , 32.3    , 32.5    , 32.7    , 32.9    ,
        33.1    , 33.2    , 33.3    , 33.5    , 33.7    , 33.9    ,
        34.1    , 34.2    , 34.4    , 34.7    , 34.9    , 35.2    ,
        35.486  , 35.7    , 35.9    , 36.1    , 36.3    , 36.6    ,
        36.8    , 37.     , 37.2    , 37.419  , 38.     , 38.2    ,
        38.63   , 39.167  , 39.504  , 39.841  , 40.378  , 41.1    ,
        41.8    , 42.489  , 43.926  , 46.31907, 46.389  ]))}

In [81]:
insurance_table_test.numerical_binned_encoding_maps

{'bmi': {None: 0,
  (np.float64(17.936999999999998), np.float64(17.96031)): 1,
  (np.float64(17.96031), np.float64(19.274)): 2,
  (np.float64(19.274), np.float64(20.0)): 3,
  (np.float64(20.0), np.float64(20.5)): 4,
  (np.float64(20.5), np.float64(21.270000000000003)): 5,
  (np.float64(21.270000000000003), np.float64(21.7)): 6,
  (np.float64(21.7), np.float64(21.858999999999998)): 7,
  (np.float64(21.858999999999998), np.float64(22.3)): 8,
  (np.float64(22.3), np.float64(22.6)): 9,
  (np.float64(22.6), np.float64(23.0)): 10,
  (np.float64(23.0), np.float64(23.2)): 11,
  (np.float64(23.2), np.float64(23.5)): 12,
  (np.float64(23.5), np.float64(23.781000000000002)): 13,
  (np.float64(23.781000000000002), np.float64(24.0)): 14,
  (np.float64(24.0), np.float64(24.255)): 15,
  (np.float64(24.255), np.float64(24.4)): 16,
  (np.float64(24.4), np.float64(24.6)): 17,
  (np.float64(24.6), np.float64(24.9)): 18,
  (np.float64(24.9), np.float64(25.2)): 19,
  (np.float64(25.2), np.float64(25.340000000000003)): 20,
  (np.float64(25.340000000000003), np.float64(25.576999999999998)): 21,
  (np.float64(25.576999999999998), np.float64(25.7)): 22,
  (np.float64(25.7), np.float64(25.8)): 23,
  (np.float64(25.8), np.float64(26.0)): 24,
  (np.float64(26.0), np.float64(26.3)): 25,
  (np.float64(26.3), np.float64(26.4)): 26,
  (np.float64(26.4), np.float64(26.699)): 27,
  (np.float64(26.699), np.float64(26.8)): 28,
  (np.float64(26.8), np.float64(27.1)): 29,
  (np.float64(27.1), np.float64(27.4)): 30,
  (np.float64(27.4), np.float64(27.5)): 31,
  (np.float64(27.5), np.float64(27.6)): 32,
  (np.float64(27.6), np.float64(27.7)): 33,
  (np.float64(27.7), np.float64(27.8)): 34,
  (np.float64(27.8), np.float64(28.0)): 35,
  (np.float64(28.0), np.float64(28.1)): 36,
  (np.float64(28.1), np.float64(28.3)): 37,
  (np.float64(28.3), np.float64(28.5)): 38,
  (np.float64(28.5), np.float64(28.643000000000008)): 39,
  (np.float64(28.643000000000008), np.float64(28.8)): 40,
  (np.float64(28.8), np.float64(28.9)): 41,
  (np.float64(28.9), np.float64(29.1)): 42,
  (np.float64(29.1), np.float64(29.4)): 43,
  (np.float64(29.4), np.float64(29.6)): 44,
  (np.float64(29.6), np.float64(29.7)): 45,
  (np.float64(29.7), np.float64(29.8)): 46,
  (np.float64(29.8), np.float64(29.9)): 47,
  (np.float64(29.9), np.float64(30.1)): 48,
  (np.float64(30.1), np.float64(30.2)): 49,
  (np.float64(30.2), np.float64(30.4)): 50,
  (np.float64(30.4), np.float64(30.5)): 51,
  (np.float64(30.5), np.float64(30.7)): 52,
  (np.float64(30.7), np.float64(30.8)): 53,
  (np.float64(30.8), np.float64(31.0)): 54,
  (np.float64(31.0), np.float64(31.135)): 55,
  (np.float64(31.135), np.float64(31.4)): 56,
  (np.float64(31.4), np.float64(31.5)): 57,
  (np.float64(31.5), np.float64(31.7)): 58,
  (np.float64(31.7), np.float64(31.8)): 59,
  (np.float64(31.8), np.float64(32.019999999999996)): 60,
  (np.float64(32.019999999999996), np.float64(32.2)): 61,
  (np.float64(32.2), np.float64(32.3)): 62,
  (np.float64(32.3), np.float64(32.5)): 63,
  (np.float64(32.5), np.float64(32.7)): 64,
  (np.float64(32.7), np.float64(32.9)): 65,
  (np.float64(32.9), np.float64(33.1)): 66,
  (np.float64(33.1), np.float64(33.2)): 67,
  (np.float64(33.2), np.float64(33.3)): 68,
  (np.float64(33.3), np.float64(33.5)): 69,
  (np.float64(33.5), np.float64(33.7)): 70,
  (np.float64(33.7), np.float64(33.9)): 71,
  (np.float64(33.9), np.float64(34.1)): 72,
  (np.float64(34.1), np.float64(34.2)): 73,
  (np.float64(34.2), np.float64(34.4)): 74,
  (np.float64(34.4), np.float64(34.7)): 75,
  (np.float64(34.7), np.float64(34.9)): 76,
  (np.float64(34.9), np.float64(35.2)): 77,
  (np.float64(35.2), np.float64(35.48600000000001)): 78,
  (np.float64(35.48600000000001), np.float64(35.7)): 79,
  (np.float64(35.7), np.float64(35.9)): 80,
  (np.float64(35.9), np.float64(36.1)): 81,
  (np.float64(36.1), np.float64(36.3)): 82,
  (np.float64(36.3), np.float64(36.6)): 83,
  (np.float64(36.6), np.float64(36.8)): 84,
  (np.float64(36.8), np.float64(37.0)): 85,
  (np.float64(37.0), np.float64(37.2)): 86,
  (np.float64(37.2), np.float64(37.419000000000004)): 87,
  (np.float64(37.419000000000004), np.float64(38.0)): 88,
  (np.float64(38.0), np.float64(38.2)): 89,
  (np.float64(38.2), np.float64(38.629999999999995)): 90,
  (np.float64(38.629999999999995), np.float64(39.16700000000001)): 91,
  (np.float64(39.16700000000001), np.float64(39.504)): 92,
  (np.float64(39.504), np.float64(39.84100000000001)): 93,
  (np.float64(39.84100000000001), np.float64(40.37799999999999)): 94,
  (np.float64(40.37799999999999), np.float64(41.1)): 95,
  (np.float64(41.1), np.float64(41.8)): 96,
  (np.float64(41.8), np.float64(42.48899999999999)): 97,
  (np.float64(42.48899999999999), np.float64(43.925999999999995)): 98,
  (np.float64(43.925999999999995), np.float64(46.31906999999996)): 99,
  (np.float64(46.31906999999996), np.float64(46.38899999999997)): 100}}

In [82]:
insurance_table_test.numerical_binned_decoding_maps["bmi"][1][0]

np.float64(17.936999999999998)

In [83]:
test_edges = insurance_table_test._column_binned_designs["bmi"].edges
test_edges

array([17.937  , 17.96031, 19.274  , 20.     , 20.5    , 21.27   ,
       21.7    , 21.859  , 22.3    , 22.6    , 23.     , 23.2    ,
       23.5    , 23.781  , 24.     , 24.255  , 24.4    , 24.6    ,
       24.9    , 25.2    , 25.34   , 25.577  , 25.7    , 25.8    ,
       26.     , 26.3    , 26.4    , 26.699  , 26.8    , 27.1    ,
       27.4    , 27.5    , 27.6    , 27.7    , 27.8    , 28.     ,
       28.1    , 28.3    , 28.5    , 28.643  , 28.8    , 28.9    ,
       29.1    , 29.4    , 29.6    , 29.7    , 29.8    , 29.9    ,
       30.1    , 30.2    , 30.4    , 30.5    , 30.7    , 30.8    ,
       31.     , 31.135  , 31.4    , 31.5    , 31.7    , 31.8    ,
       32.02   , 32.2    , 32.3    , 32.5    , 32.7    , 32.9    ,
       33.1    , 33.2    , 33.3    , 33.5    , 33.7    , 33.9    ,
       34.1    , 34.2    , 34.4    , 34.7    , 34.9    , 35.2    ,
       35.486  , 35.7    , 35.9    , 36.1    , 36.3    , 36.6    ,
       36.8    , 37.     , 37.2    , 37.419  , 38.     , 38.2    ,
       38.63   , 39.167  , 39.504  , 39.841  , 40.378  , 41.1    ,
       41.8    , 42.489  , 43.926  , 46.31907, 46.389  ])

In [84]:
insurance_data.head(10)

    age     sex   bmi  children smoker     region      charges
0   NaN  female  27.9         0    yes  southwest  16884.92400
1   NaN    male  33.8         1     no  southeast   1725.55230
2  28.0    None  33.0         3     no  southeast   4449.46200
3  33.0    male  22.7        14     no  northwest  21984.47061
4  32.0    male  28.9         0     no  northwest   3866.85520
5  31.0  female  25.7         0     no  southeast   3756.62160
6  46.0  female  33.4         1     no  southeast   8240.58960
7  37.0  female  27.7         3     no  northwest   7281.50560
8  37.0    male  29.8         2     no  northeast   6406.41070
9  60.0  female  25.8         0     no  northwest  28923.13692

In [85]:
insurance_table_test.table.head(10)

   age  sex  bmi  children  smoker  region      charges
0    0    2   35         0       1       2  16884.92400
1    0    0   71         1       0       3   1725.55230
2   11    1   66         3       0       3   4449.46200
3   16    0   10         5       0       1  21984.47061
4   15    0   42         0       0       1   3866.85520
5   14    2   23         0       0       3   3756.62160
6   29    2   69         1       0       3   8240.58960
7   20    2   34         3       0       1   7281.50560
8   20    0   47         2       0       0   6406.41070
9   43    2   24         0       0       1  28923.13692

In [86]:
from src.utils.argn_encoder_decoder import decode_numerical_binned, decode_categorical, decode_numerical_discrete

In [87]:
decode_numerical_binned(
    insurance_table_test._table,
    insurance_table_test.numerical_binned_decoding_maps,
    [item[0] for item in insurance_table_test._numerical_binned_columns]
)

shape: (1_338, 7)
┌─────┬─────┬───────────┬──────────┬────────┬────────┬─────────────┐
│ age ┆ sex ┆ bmi       ┆ children ┆ smoker ┆ region ┆ charges     │
│ --- ┆ --- ┆ ---       ┆ ---      ┆ ---    ┆ ---    ┆ ---         │
│ i64 ┆ i64 ┆ f64       ┆ i64      ┆ i64    ┆ i64    ┆ f64         │
╞═════╪═════╪═══════════╪══════════╪════════╪════════╪═════════════╡
│ 0   ┆ 2   ┆ 27.874908 ┆ 0        ┆ 1      ┆ 2      ┆ 16884.924   │
│ 0   ┆ 0   ┆ 33.890143 ┆ 1        ┆ 0      ┆ 3      ┆ 1725.5523   │
│ 11  ┆ 1   ┆ 33.046399 ┆ 3        ┆ 0      ┆ 3      ┆ 4449.462    │
│ 16  ┆ 0   ┆ 22.839463 ┆ 5        ┆ 0      ┆ 1      ┆ 21984.47061 │
│ 15  ┆ 0   ┆ 28.931204 ┆ 0        ┆ 0      ┆ 1      ┆ 3866.8552   │
│ …   ┆ …   ┆ …         ┆ …        ┆ …      ┆ …      ┆ …           │
│ 33  ┆ 0   ┆ 31.134505 ┆ 3        ┆ 0      ┆ 1      ┆ 10600.5483  │
│ 1   ┆ 2   ┆ 32.014454 ┆ 0        ┆ 0      ┆ 0      ┆ 2205.9808   │
│ 1   ┆ 2   ┆ 36.930065 ┆ 0        ┆ 0      ┆ 3      ┆ 1629.8335   │
│ 4   ┆ 2   ┆ 25.839908 ┆ 0        ┆ 0      ┆ 2      ┆ 2007.945    │
│ 44  ┆ 2   ┆ 29.304068 ┆ 0        ┆ 1      ┆ 1      ┆ 29141.3603  │
└─────┴─────┴───────────┴──────────┴────────┴────────┴─────────────┘

In [88]:
insurance_data.head(10)

    age     sex   bmi  children smoker     region      charges
0   NaN  female  27.9         0    yes  southwest  16884.92400
1   NaN    male  33.8         1     no  southeast   1725.55230
2  28.0    None  33.0         3     no  southeast   4449.46200
3  33.0    male  22.7        14     no  northwest  21984.47061
4  32.0    male  28.9         0     no  northwest   3866.85520
5  31.0  female  25.7         0     no  southeast   3756.62160
6  46.0  female  33.4         1     no  southeast   8240.58960
7  37.0  female  27.7         3     no  northwest   7281.50560
8  37.0    male  29.8         2     no  northeast   6406.41070
9  60.0  female  25.8         0     no  northwest  28923.13692

In [89]:
decode_categorical(
    insurance_table_test._table,
    insurance_table_test.categorical_decoding_maps ,
    [item[0] for item in insurance_table_test._categorical_columns]
)

shape: (1_338, 7)
┌─────┬────────┬─────┬──────────┬────────┬───────────┬─────────────┐
│ age ┆ sex    ┆ bmi ┆ children ┆ smoker ┆ region    ┆ charges     │
│ --- ┆ ---    ┆ --- ┆ ---      ┆ ---    ┆ ---       ┆ ---         │
│ i64 ┆ str    ┆ i64 ┆ i64      ┆ str    ┆ str       ┆ f64         │
╞═════╪════════╪═════╪══════════╪════════╪═══════════╪═════════════╡
│ 0   ┆ female ┆ 35  ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   │
│ 0   ┆ male   ┆ 71  ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   │
│ 11  ┆ null   ┆ 66  ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    │
│ 16  ┆ male   ┆ 10  ┆ 5        ┆ no     ┆ northwest ┆ 21984.47061 │
│ 15  ┆ male   ┆ 42  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   │
│ …   ┆ …      ┆ …   ┆ …        ┆ …      ┆ …         ┆ …           │
│ 33  ┆ male   ┆ 55  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  │
│ 1   ┆ female ┆ 60  ┆ 0        ┆ no     ┆ northeast ┆ 2205.9808   │
│ 1   ┆ female ┆ 85  ┆ 0        ┆ no     ┆ southeast ┆ 1629.8335   │
│ 4   ┆ female ┆ 24  ┆ 0        ┆ no     ┆ southwest ┆ 2007.945    │
│ 44  ┆ female ┆ 43  ┆ 0        ┆ yes    ┆ northwest ┆ 29141.3603  │
└─────┴────────┴─────┴──────────┴────────┴───────────┴─────────────┘

In [90]:
[item[0] for item in insurance_table_test._categorical_columns]

['sex', 'smoker', 'region']

In [91]:
[item[0] for item in insurance_table_test._numerical_discrete_columns]

['age', 'children']

In [92]:
insurance_table_test.numerical_discrete_encoding_maps

{'age': {None: 0,
  18: 1,
  19: 2,
  20: 3,
  21: 4,
  22: 5,
  23: 6,
  24: 7,
  25: 8,
  26: 9,
  27: 10,
  28: 11,
  29: 12,
  30: 13,
  31: 14,
  32: 15,
  33: 16,
  34: 17,
  35: 18,
  36: 19,
  37: 20,
  38: 21,
  39: 22,
  40: 23,
  41: 24,
  42: 25,
  43: 26,
  44: 27,
  45: 28,
  46: 29,
  47: 30,
  48: 31,
  49: 32,
  50: 33,
  51: 34,
  52: 35,
  53: 36,
  54: 37,
  55: 38,
  56: 39,
  57: 40,
  58: 41,
  59: 42,
  60: 43,
  61: 44,
  62: 45,
  63: 46,
  64: 47},
 'children': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}}

In [93]:
insurance_table_test._numerical_discrete_columns

[('age', 0), ('children', 3)]

In [101]:
decode_numerical_discrete(
    insurance_table_test._table,
    insurance_table_test.numerical_discrete_decoding_maps,
    [item[0] for item in insurance_table_test._numerical_discrete_columns]    
).head(10)

shape: (10, 7)
┌──────┬─────┬─────┬──────────┬────────┬────────┬─────────────┐
│ age  ┆ sex ┆ bmi ┆ children ┆ smoker ┆ region ┆ charges     │
│ ---  ┆ --- ┆ --- ┆ ---      ┆ ---    ┆ ---    ┆ ---         │
│ i64  ┆ i64 ┆ i64 ┆ i64      ┆ i64    ┆ i64    ┆ f64         │
╞══════╪═════╪═════╪══════════╪════════╪════════╪═════════════╡
│ null ┆ 2   ┆ 35  ┆ 0        ┆ 1      ┆ 2      ┆ 16884.924   │
│ null ┆ 0   ┆ 71  ┆ 1        ┆ 0      ┆ 3      ┆ 1725.5523   │
│ 28   ┆ 1   ┆ 66  ┆ 3        ┆ 0      ┆ 3      ┆ 4449.462    │
│ 33   ┆ 0   ┆ 10  ┆ 5        ┆ 0      ┆ 1      ┆ 21984.47061 │
│ 32   ┆ 0   ┆ 42  ┆ 0        ┆ 0      ┆ 1      ┆ 3866.8552   │
│ 31   ┆ 2   ┆ 23  ┆ 0        ┆ 0      ┆ 3      ┆ 3756.6216   │
│ 46   ┆ 2   ┆ 69  ┆ 1        ┆ 0      ┆ 3      ┆ 8240.5896   │
│ 37   ┆ 2   ┆ 34  ┆ 3        ┆ 0      ┆ 1      ┆ 7281.5056   │
│ 37   ┆ 0   ┆ 47  ┆ 2        ┆ 0      ┆ 0      ┆ 6406.4107   │
│ 60   ┆ 2   ┆ 24  ┆ 0        ┆ 0      ┆ 1      ┆ 28923.13692 │
└──────┴─────┴─────┴──────────┴────────┴────────┴─────────────┘

In [95]:
insurance_data.head(10)

    age     sex   bmi  children smoker     region      charges
0   NaN  female  27.9         0    yes  southwest  16884.92400
1   NaN    male  33.8         1     no  southeast   1725.55230
2  28.0    None  33.0         3     no  southeast   4449.46200
3  33.0    male  22.7        14     no  northwest  21984.47061
4  32.0    male  28.9         0     no  northwest   3866.85520
5  31.0  female  25.7         0     no  southeast   3756.62160
6  46.0  female  33.4         1     no  southeast   8240.58960
7  37.0  female  27.7         3     no  northwest   7281.50560
8  37.0    male  29.8         2     no  northeast   6406.41070
9  60.0  female  25.8         0     no  northwest  28923.13692

In [99]:
for col, enc_map in insurance_table_test.numerical_discrete_encoding_maps.items():
    print(f"{col}: {list(enc_map.items())[:15]}")

age: [(None, 0), (18, 1), (19, 2), (20, 3), (21, 4), (22, 5), (23, 6), (24, 7), (25, 8), (26, 9), (27, 10), (28, 11), (29, 12), (30, 13), (31, 14)]
children: [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]

In [ ]:
# Numeric Digit

In [128]:
b = [16884, 1725, 23, -1, 0, pd.NA, np.nan, None, np.inf]

In [134]:
[str(abs(item)) if not (pd.isna(item) or np.isinf(item)) else None for item in b]

['16884', '1725', '23', '1', '0', None, None, None, None]

In [ ]:
[
    None     if pd.isna(item)           else
    None     if not np.isfinite(item)   else   
    0        if item >= 0               else
    -1
    for item in b
]

[0, 0, 0, -1, 0, None, None, None, None]

In [ ]:
# I need to pad the digits with zeros to the left and the decimals with zeros to the right

def pad_numeric_digit_col(string_numbers: list[str], max_len: int, direction: str) -> list[str]:
   """
   Assumes a list of numbers casted into strings and returns a list of string 
   containing the same numbers bud padded with zeros on the left for digits
   [direction == "left"] or right for decimals [direction == "right"]

   Parameters:
   ----------

   string_numbers : list[str]
        A list of numbers casted as strings to process
   max_len : int
        The maximun length of the string numbers. The every string number in 
        the list will be paddded with zeros up until the length of the padded
        number is equal to max_len
   direction : str, ["left", "right"]
        The direction of the padding. Left adds zeroes to the left of the 
        string number (digits case) and right adds the zeros to the right of
        the number (decimal case).
    
   Returns:
   -------

   processed_number_strings : list[str]
        A list of padded string numbers

   Warns:
   -----

   If string_numbers is empty

   Raises:
   ------

   ValueError
      If the parameter direction is not equal to either 'right' or 'left'

   """

   if direction not in ["right", "left"]:
        raise ValueError(f"The direction parameter only accepts 'right' or 'left values. Client provided {direction}...")
    
   if len(string_numbers) == 0:
        warnings.warn("No numbers were provided to the padding step...")
        return []
   
   processed_number_strings = []

   for item in string_numbers:
       if pd.isna(item):
           padded_value = '0'*max_len
           processed_number_strings.append(padded_value)
       elif len(item) == max_len:
           processed_number_strings.append(item)
       else:
           pad_needed = max_len - len(item)
           generated_pad = '0'*pad_needed
           if direction == 'left':
               padded_value = generated_pad + item
               processed_number_strings.append(padded_value)
           else:
               padded_value = item + generated_pad
               processed_number_strings.append(padded_value)

   return processed_number_strings

In [152]:
b = ['16884', '1725', '23', '7', '0', None]
pad_numeric_digit_col(b, len(b[0]), 'right')

['16884', '17250', '23000', '70000', '00000', '00000']

In [155]:
c = ['16884', '1725', '23', '7', '0']
d = ['0', '0', '0', '0', '0']
e = [f"{prefix}{value}" for prefix, value in zip(d,c)]
e

['016884', '01725', '023', '07', '00']

In [157]:
f = ['1', '1', '1', '1', '1']
g = [f"{prefix}{value}" for prefix, value in zip(e,f)]
g

['0168841', '017251', '0231', '071', '001']

In [158]:
def generate_sub_column_values(df_pl: pl.DataFrame, col_name: str) -> tuple[int, list[str]]:
    """
    Assumes a polars data frame and a column name with float values to be
    encoded following the DIGIT strategy, which generates sub columns.

    Parameters:
    ----------

    df_pl : pl.DataFrame
        A polars data fra,e
    col_name : str
        The name of the column with float values to process
    
    Returns:
    -------

    n_sub_cols, sub_column_values_as_string : tuple[int, list[str]]
        n_sub_cols, the number of sub-columns required to encode col_name 
        following the DIGIT strategy
        sub_column_values_as_string, the values for each sub-column, starting
        with a binary column for the sign of the float, the float number 
        padded with zeros in both sides, and finally a binary column 
        to indicate missing values
    """

    list_to_process = df_pl[col_name].to_list()

    # The first sub column will have a vocabulary of {1, 0}. A value equal to 0 for positive numbers and 1 for negative numbers.
    # In this step we also collect the missing values. There values will have a column with a vocabulary of {0, 1} in the 
    # sub-columns scheme. The scheme for the sub-columns will be [sign, digit, ..., digit, decimal, ..., missing] with vocabularies
    # equal to [{0,1}, {0-9}, ..., {0-9}, {0-9}, {0, 1}] 
    signs_of_items =  [
    '0'     if pd.isna(item)           else
    '0'     if not np.isfinite(item)   else   
    '0'     if item >= 0               else
    '1'
    for item in list_to_process
    ]

    missing_in_items =  [
    '1'     if pd.isna(item)           else
    '1'     if not np.isfinite(item)   else   
    '0'     
    for item in list_to_process
    ]

    # The next step is converting the float values into strings for processing. Missing values and np.inf are both treated as missing 
    col_vals_as_strings = [str(abs(item)) if not (pd.isna(item) or np.isinf(item))  else None for item in list_to_process] 

    # Separating digints from decimals in two distinct lists
    digits_in_numbers, decimals_in_numbers = zip(*[tuple(item.split(".")) for item in col_vals_as_strings])

    # Computing length of digits
    len_digits_in_numbers = [len(item) for item in digits_in_numbers]
    n_digit_sub_cols = max(len_digits_in_numbers)

    # Computing length of decimals
    len_decimals_in_numbers = [len(item) for item in decimals_in_numbers]
    n_decimal_sub_cols = max(len_decimals_in_numbers)

    # Computing number of required sub-columns for the variable being processed
    n_sub_cols = n_digit_sub_cols + n_decimal_sub_cols + 1  + 1 # Adding one for a sub-column to store the sign and another to store NAs

    # Padding digits
    padded_digits = pad_numeric_digit_col(digits_in_numbers, n_digit_sub_cols, 'left')

    # Padding decimals
    padded_decimals = pad_numeric_digit_col(decimals_in_numbers, n_decimal_sub_cols, 'right')

    # Generating the values for all sub-columns as strings
    signs_and_pad_digits = [f"{prefix}{value}" for prefix, value in zip(signs_of_items, padded_digits)]
    signs_and_pad_digits_and_decimals = [f"{prefix}{value}" for prefix, value in zip(signs_and_pad_digits, padded_decimals)]
    sub_column_values_as_string = [f"{prefix}{value}" for prefix, value in zip(signs_and_pad_digits_and_decimals, missing_in_items)]

    return n_sub_cols, sub_column_values_as_string

In [ ]:
col_name = "charges"
df_pl = insurance_table_test._table

In [159]:
generate_sub_column_values(df_pl, col_name)

(13,
 ['0168849240000',
  '0017255523000',
  '0044494620000',
  '0219844706100',
  '0038668552000',
  '0037566216000',
  '0082405896000',
  '0072815056000',
  '0064064107000',
  '0289231369200',
  '0027213208000',
  '0278087251000',
  '0018268430000',
  '0110907178000',
  '0396117577000',
  '0018372370000',
  '0107973362000',
  '0023951715500',
  '0106023850000',
  '0368374670000',
  '0132288469500',
  '0041497360000',
  '0012529727300',
  '0377018768000',
  '0062039017500',
  '0140011338000',
  '0144518351500',
  '0122686322500',
  '0027751921500',
  '0387110000000',
  '0355855760000',
  '0021981898500',
  '0046877970000',
  '0137700979000',
  '0485374807260',
  '0016254337500',
  '0156121933500',
  '0023023000000',
  '0397742763000',
  '0481733610000',
  '0030460620000',
  '0049497587000',
  '0062724772000',
  '0063137590000',
  '0060796715000',
  '0206302835100',
  '0033933563500',
  '0035569223000',
  '0126298967000',
  '0387091760000',
  '0022111307500',
  '0035798287000',
  '0235682720000',
  '0377425757000',
  '0080596791000',
  '0474964944500',
  '0136073687500',
  '0343031672000',
  '0232447902000',
  '0059895236500',
  '0086062174000',
  '0045046624000',
  '0301666181700',
  '0041336416500',
  '0147117438000',
  '0017432140000',
  '0142350720000',
  '0063893778500',
  '0059201041000',
  '0176631442000',
  '0165777795000',
  '0067994580000',
  '0117417260000',
  '0119466259000',
  '0077268540000',
  '0113566609000',
  '0039474131000',
  '0015324697000',
  '0027550209500',
  '0065710243500',
  '0044412131500',
  '0079352911500',
  '0371651638000',
  '0110336617000',
  '0398365190000',
  '0210985540500',
  '0435789394000',
  '0110731760000',
  '0080266666000',
  '0110825772000',
  '0020269741000',
  '0109421320500',
  '0301849367000',
  '0057290053000',
  '0472910550000',
  '0037668838000',
  '0121053200000',
  '0102262842000',
  '0224126485000',
  '0158206990000',
  '0061861270000',
  '0036450894000',
  '0213448467000',
  '0309421918000',
  '0050038530000',
  '0175603797500',
  '0023315190000',
  '0038773042500',
  '0028671196000',
  '0470555321000',
  '0108252537000',
  '0118813580000',
  '0046467590000',
  '0024047338000',
  '0114883169500',
  '0302599955600',
  '0113813254000',
  '0191077796000',
  '0086013293000',
  '0066864313000',
  '0077403370000',
  '0017056245000',
  '0022574752500',
  '0395564945000',
  '0101150088500',
  '0033853991500',
  '0170810800000',
  '0096345380000',
  '0327341863000',
  '0060824050000',
  '0128154449500',
  '0136163586000',
  '0111635680000',
  '0016325644500',
  '0024572111500',
  '0021556815000',
  '0012614420000',
  '0020456852500',
  '0273227338600',
  '0021667320000',
  '0273759047800',
  '0034905491000',
  '0189724950000',
  '0181578760000',
  '0207459891000',
  '0051382567000',
  '0407205510500',
  '0098776077000',
  '0109596947000',
  '0018425190000',
  '0051252157000',
  '0077896350000',
  '0063343435500',
  '0199647463000',
  '0070771894000',
  '0069487008000',
  '0212236758000',
  '0155181802500',
  '0369502567000',
  '0197493833800',
  '0213487060000',
  '0361494835000',
  '0104505520000',
  '0051521340000',
  '0050281466000',
  '0104070858500',
  '0048306300000',
  '0061287974500',
  '0027192797500',
  '0048279049500',
  '0134053903000',
  '0081166800000',
  '0016947964000',
  '0052460470000',
  '0028554375500',
  '0485374807260',
  '0064558626500',
  '0104360960000',
  '0088232790000',
  '0085382884500',
  '0117358790500',
  '0016318212000',
  '0040054225000',
  '0074194779000',
  '0077314271000',
  '0437533370500',
  '0039819768000',
  '0053256510000',
  '0067759610000',
  '0049229159000',
  '0125576053000',
  '0048838660000',
  '0021376536000',
  '0120443420000',
  '0012529727300',
  '0016395631000',
  '0056497150000',
  '0085168290000',
  '0096442525000',
  '0149015167000',
  '0021306759000',
  '0088711517000',
  '0130122086500',
  '0371338982000',
  '0071471050000',
  '0043377352000',
  '0117432990000',
  '0209840936000',
  '0138809490000',
  '0066101097000',
  '0019800700000',
  '0081627162500',
  '0035377030000',
  '0050027827000',
  '0085200260000',
  '0073717720000',
  '0103556410000',
  '0024837360000',
  '0033929768000',
  '0250817678400',
  '0050124710000',
  '0105648845000',
  '0052535240000',
  '0347796150000',
  '0195155416000',
  '0119871682000',
  '0026894954000',
  '0242273372400',
  '0073581756500',
  '0092252564000',
  '0074436430500',
  '0140012867000',
  '0017277850000',
  '0123338280000',
  '0067101919000',
  '0194442658000',
  '0016157667000',
  '0044632051000',
  '0173526803000',
  '0071526714000',
  '0385116283000',
  '0053540746500',
  '0351601345700',
  '0071968670000',
  '0295231656000',
  '0244764785100',
  '0126487034000',
  '0019869334000',
  '0018320940000',
  '0040405582500',
  '0128294551000',
  '0473053050000',
  '0442607499000',
  '0042607440000',
  '0410971617500',
  '0130473323500',
  '0439211837000',
  '0054009805000',
  '0115200998500',
  '0337502918000',
  '0118371600000',
  '0170852676000',
  '0248698368000',
  '0362194054500',
  '0204629976600',
  '0461511245000',
  '0171795220000',
  '0145906320500',
  '0074410530000',
  '0092824806000',
  '0017194363000',
  '0428568380000',
  '0072657025000',
  '0096176624500',
  '0025231695000',
  '0097158410000',
  '0028036978500',
  '0021504690000',
  '0129287911000',
  '0098551314000',
  '0223315668000',
  '0485374807260',
  '0042371265500',
  '0118791040500',
  '0096259200000',
  '0077421098000',
  '0094329253000',
  '0142561928000',
  '0478967913500',
  '0259928210400',
  '0031720180000',
  '0202778075100',
  '0421122356000',
  '0021567518000',
  '0039061270000',
  '0017045681000',
  '0162978460000',
  '0219786769000',
  '0387463551000',
  '0092494952000',
  '0067467425000',
  '0248733849000',
  '0122655069000',
  '0043494620000',
  '0126462070000',
  '0194423535000',
  '0201776711300',
  '0041510287000',
  '0119445943500',
  '0077491564000',
  '0084444740000',
  '0017373760000',
  '0421245153000',
  '0081244084000',
  '0348388730000',
  '0097227695000',
  '0088352649500',
  '0104350652500',
  '0074211945500',
  '0046676076500',
  '0048947533000',
  '0246716633400',
  '0354916400000',
  '0115663005500',
  '0028660910000',
  '0066002059500',
  '0035618889000',
  '0427605022000',
  '0479280300000',
  '0091445650000',
  '0485175631500',
  '0243936224000',
  '0134290354000',
  '0116583791500',
  '0191445765200',
  '0138228030000',
  '0121425786000',
  '0139376665000',
  '0419190970000',
  '0082326388000',
  '0189552201700',
  '0133520998000',
  '0132170945000',
  '0139818503500',
  '0109772063000',
  '0061842994000',
  '0048899995000',
  '0083344575500',
  '0054780368000',
  '0016357336500',
  '0118306072000',
  '0089320840000',
  '0035542030000',
  '0124048791000',
  '0141330377500',
  '0246030483700',
  '0089441151000',
  '0096203307000',
  '0018372819000',
  '0016075101000',
  '0100432490000',
  '0047510700000',
  '0138445060000',
  '0025977790000',
  '0031805101000',
  '0097783472000',
  '0134302650000',
  '0080170611500',
  '0081162688500',
  '0034818680000',
  '0134150381000',
  '0120292867000',
  '0076394174500',
  '0360852190000',
  '0013915287000',
  '0180339679000',
  '0216599301000',
  '0381262465000',
  '0164557078500',
  '0270009847300',
  '0150065794500',
  '0423036921500',
  '0207814889200',
  '0058469176000',
  '0083025356500',
  '0012618590000',
  '0118564115000',
  '0302846429400',
  '0031768159000',
  '0046180799000',
  '0107368707500',
  '0021380707000',
  '0089640605500',
  '0092901395000',
  '0094110050000',
  '0075267064500',
  '0085220030000',
  '0165864977100',
  '0149884320000',
  '0016316683000',
  '0092647970000',
  '0080839198000',
  '0146926693500',
  '0102694600000',
  '0032601990000',
  '0113969002000',
  '0041850979000',
  '0085396710000',
  '0066525288000',
  '0040744537000',
  '0016213402000',
  '0195948096500',
  '0144556440500',
  '0050800960000',
  '0021349015000',
  '0073457266000',
  '0091409510000',
  '0186082620000',
  '0144182804000',
  '0289504692000',
  '0468892612000',
  '0465991084000',
  '0391253322500',
  '0027273951000',
  '0089683300000',
  '0097888659000',
  '0065550703500',
  '0073237348190',
  '0031674558500',
  '0188047524000',
  '0230829553300',
  '0049064096500',
  '0059697230000',
  '0126381950000',
  '0042435900500',
  '0139198229000',
  '0022547967000',
  '0059268460000',
  '0125925345000',
  '0028973235000',
  '0047382682000',
  '0370793720000',
  '0012529727300',
  '0282878976600',
  '0261093290500',
  '0073450840000',
  '0127309996000',
  '0114540215000',
  '0059109440000',
  '0047623290000',
  '0075122670000',
  '0040322407000',
  '0019696140000',
  '0017695316500',
  '0046863887000',
  '0217970004000',
  '0118819696000',
  '0118407750500',
  '0106014120000',
  '0076826700000',
  '0103814787000',
  '0221440320000',
  '0152303240500',
  '0111654176500',
  '0016320362500',
  '0195219682000',
  '0132246930000',
  '0126433778000',
  '0232889284000',
  '0022010971000',
  '0024970383000',
  '0022034718500',
  '0017444650000',
  '0208787844300',
  '0253822970000',
  '0288686639000',
  '0351475284800',
  '0025343937500',
  '0015343045000',
  '0018242854000',
  '0155551887500',
  '0093047019000',
  '0016221885000',
  '0098800680000',
  '0095630290000',
  '0043470233500',
  '0124753513000',
  '0012539360000',
  '0485374807260',
  '0104619794000',
  '0017487740000',
  '0245130912600',
  '0021964732000',
  '0125740490000',
  '0179421060000',
  '0019670227000',
  '0049316470000',
  '0080279680000',
  '0082111002000',
  '0134708600000',
  '0361976990000',
  '0068373687000',
  '0222181149000',
  '0325483405000',
  '0059743847000',
  '0067968632500',
  '0026432685000',
  '0030770955000',
  '0030442133000',
  '0114552800000',
  '0117630009000',
  '0024984144000',
  '0093613268000',
  '0012562990000',
  '0210821600000',
  '0113627550000',
  '0277242887500',
  '0084134630500',
  '0052407650000',
  '0038577592500',
  '0256565752600',
  '0039941778000',
  '0098663048500',
  '0053976167000',
  '0382455932700',
  '0114826348500',
  '0240596801900',
  '0098610250000',
  '0083429087500',
  '0017080014000',
  '0485374807260',
  '0140434767000',
  '0129258860000',
  '0192147055300',
  '0138311152000',
  '0060671267500',
  '0059723780000',
  '0088250860000',
  '0082330975000',
  '0273460420700',
  '0061964480000',
  '0030563881000',
  '0138872040000',
  '0485374807260',
  '0102314999000',
  '0238072406000',
  '0032688466500',
  '0115384210000',
  '0032136220500',
  '0458632050000',
  '0133905590000',
  '0039729247000',
  '0129571180000',
  '0111876567000',
  '0178789006800',
  '0038476740000',
  '0083345896000',
  '0039351799000',
  '0399834259500',
  '0016464297000',
  '0091938385000',
  '0109239332000',
  '0024940220000',
  '0090587303000',
  '0028012588000',
  '0021284310500',
  '0063735573500',
  '0072567231000',
  '0115529040000',
  '0457020223500',
  '0037612920000',
  '0022194451000',
  '0047536368000',
  '0316200010600',
  '0132240570500',
  '0122228983000',
  '0016649996000',
  '0485374807260',
  '0097245300000',
  '0032064913500',
  '0129139924000',
  '0016395631000',
  '0063562707000',
  '0176262395100',
  '0012529727300',
  '0047796023000',
  '0038612096500',
  '0439438761000',
  '0136356379000',
  '0059768311000',
  '0118424420000',
  '0084280693000',
  '0025664707000',
  '0153591045000',
  '0057091644000',
  '0088239857500',
  '0076403092000',
  '0055948455000',
  '0074415010000',
  '0334719718900',
  '0016330444000',
  '0091741356500',
  '0110705350000',
  '0160851275000',
  '0174689839000',
  '0092835620000',
  '0035586202500',
  '0256787784500',
  '0044350942000',
  '0392414420000',
  '0085476913000',
  '0065715440000',
  '0022076974500',
  '0067530380000',
  '0018800700000',
  '0429698527000',
  '0116581150500',
  '0233065470000',
  '0344398559000',
  '0107136440000',
  '0036593460000',
  '0401822460000',
  '0091821700000',
  '0346178406500',
  '0121296141500',
  '0037364647000',
  '0067485912000',
  '0113267148700',
  '0113659520000',
  '0429834585000',
  '0100858460000',
  '0019778150000',
  '0033666697000',
  '0071733599500',
  '0093913460000',
  '0144109321000',
  '0027091119000',
  '0249150462600',
  '0201493229000',
  '0129491554000',
  '0066662430000',
  '0327874585900',
  '0131438648500',
  '0044666214000',
  '0188061454700',
  '0101411362000',
  '0061235688000',
  '0082522843000',
  '0017122270000',
  '0124309533500',
  '0098008882000',
  '0105797110000',
  '0082806227000',
  '0085275320000',
  '0122445310000',
  '0246674190000',
  '0034103240000',
  '0040587124500',
  '0263922602900',
  '0143943981500',
  '0064356237000',
  '0221924371100',
  '0051485526000',
  '0012529727300',
  '0270379141000',
  '0425604304000',
  '0087034560000',
  '0400033322500',
  '0457102078500',
  '0065002359000',
  '0048375823000',
  '0039435954000',
  '0043997310000',
  '0061853208000',
  '0462009851000',
  '0072227862500',
  '0124858009000',
  '0461305265000',
  '0123635470000',
  '0101567832000',
  '0025852690000',
  '0012529727300',
  '0401038900000',
  '0098634718000',
  '0047660220000',
  '0112443769000',
  '0077296457500',
  '0054387491000',
  '0262365799700',
  '0348064677000',
  '0021041134000',
  '0080681850000',
  '0023622290500',
  '0023529684500',
  '0035779990000',
  '0032012451500',
  '0291864823600',
  '0402736455000',
  '0109762457500',
  '0035006123000',
  '0020205523000',
  '0095416955500',
  '0095043103000',
  '0053853379000',
  '0089309345500',
  '0053750380000',
  '0444004064000',
  '0102644421000',
  '0061132310500',
  '0054690066000',
  '0017275400000',
  '0101072206000',
  '0083108391500',
  '0019844533000',
  '0024575020000',
  '0121469710000',
  '0095669909000',
  '0131126048000',
  '0108481343000',
  '0122316136000',
  '0098756804000',
  '0112645410000',
  '0129793580000',
  '0012632490000',
  '0101061342500',
  '0409324295000',
  '0066646859500',
  '0166577174500',
  '0022176012000',
  '0067813542000',
  '0193619988000',
  '0100654130000',
  '0042349270000',
  '0094472503500',
  '0140072220000',
  '0095838933000',
  '0404190191000',
  '0034843310000',
  '0361891017000',
  '0445854558700',
  '0086044836500',
  '0182464955000',
  '0432544179500',
  '0037578448000',
  '0088272099000',
  '0099103598500',
  '0117378488400',
  '0016272824500',
  '0085569070000',
  '0030625082500',
  '0195392430000',
  '0019063582500',
  '0142105359500',
  '0118337823000',
  '0171284260800',
  '0050312695500',
  '0079858150000',
  '0230654207000',
  '0054287277000',
  '0363077983000',
  '0039257582000',
  '0024169550000',
  '0190408760000',
  '0030708087000',
  '0090950682500',
  '0118426237500',
  '0080627640000',
  '0070506420000',
  '0143190310000',
  '0069332422500',
  '0279412875800',
  '0111507800000',
  '0127972096200',
  '0177485062000',
  '0072617410000',
  '0105604917000',
  '0069866970000',
  '0074484039500',
  '0059343798000',
  '0098698102000',
  '0182592160000',
  '0012529727300',
  '0093861613000',
  '0245202640000',
  '0043505144000',
  '0064141780000',
  '0127411674500',
  '0019173184000',
  '0052095788500',
  '0134579608000',
  '0056622250000',
  '0012529727300',
  '0027319122000',
  '0211958180000',
  '0072094918000',
  '0183107420000',
  '0042661658000',
  '0047195240500',
  '0118481410000',
  '0179045270500',
  '0070467222000',
  '0143138463000',
  '0021030800000',
  '0387926856000',
  '0018158759000',
  '0077318578500',
  '0284767349900',
  '0021368822500',
  '0012529727300',
  '0033097926000',
  '0094149200000',
  '0063609936000',
  '0110137119000',
  '0044288878500',
  '0055843057000',
  '0018779294000',
  '0028427607500',
  '0035975960000',
  '0234013057500',
  '0485374807260',
  '0074459180000',
  '0026809493000',
  '0016218827000',
  '0082192039000',
  '0125236048000',
  '0160690847500',
  '0438138661000',
  '0207736277500',
  '0395974072000',
  '0061174945000',
  '0133937560000',
  '0052663656000',
  '0047197365500',
  '0117439341000',
  '0053774578000',
  '0071603303000',
  '0044022330000',
  '0116577189000',
  '0064022913500',
  '0126221795000',
  '0015263120000',
  '0123239360000',
  '0360210112000',
  '0275339129000',
  '0100720550500',
  '0450089555000',
  '0098727010000',
  '0024380552000',
  '0029741260000',
  '0106016322500',
  '0372701512000',
  '0141196200000',
  '0421116647000',
  '0117296795000',
  '0241069125500',
  '0018753440000',
  '0409741649000',
  '0158179857000',
  '0182181613900',
  '0109654460000',
  '0461135110000',
  '0071510920000',
  '0122696886500',
  '0054580464500',
  '0087824690000',
  '0066003610000',
  '0012529727300',
  '0115761300000',
  '0131296034500',
  '0043916520000',
  '0084578180000',
  '0033923652000',
  '0059668874000',
  '0068490260000',
  '0088911395000',
  '0026901138000',
  '0261403603000',
  '0066537886000',
  '0062822350000',
  '0063119520000',
  '0034430640000',
  '0027890574000',
  '0025858506500',
  '0462551125000',
  '0048779810500',
  '0197196947000',
  '0272184372500',
  '0052721758000',
  '0016825970000',
  '0119451327000',
  '0293309831500',
  '0072438136000',
  '0104229166500',
  '0442026536000',
  '0135550049000',
  '0130638830000',
  '0197980545500',
  '0022215644500',
  '0016345734000',
  '0021173388500',
  '0086888588500',
  '0485374807260',
  '0046612863500',
  '0081257845000',
  '0126445890000',
  '0045641914500',
  '0048469201500',
  '0076337206000',
  '0151700690000',
  '0174963060000',
  '0026390429000',
  '0337326867000',
  '0143827090500',
  '0076269930000',
  '0052575079500',
  '0024733341000',
  '0217743221500',
  '0350693745200',
  '0130419210000',
  '0052452269000',
  '0134511220000',
  '0134625200000',
  '0054882620000',
  '0043204108500',
  '0062504350000',
  '0253333328400',
  '0029135690000',
  '0120323260000',
  '0134708044000',
  '0062897549000',
  '0029270647000',
  '0062382980000',
  '0100969700000',
  '0073481420000',
  '0046733922000',
  '0122338280000',
  '0321086628200',
  '0089657957500',
  '0023040022000',
  '0094876442000',
  '0012529727300',
  '0095495651000',
  '0022174691500',
  '0016284709000',
  '0129828747000',
  '0116741300000',
  '0071600940000',
  '0390472850000',
  '0063587764500',
  '0199334580000',
  '0115348726500',
  '0474628940000',
  '0045271829500',
  '0389985460000',
  '0200096336500',
  '0038757341000',
  '0419995200000',
  '0126098870200',
  '0410342214000',
  '0284689190100',
  '0027301078500',
  '0033532840000',
  '0144746750000',
  '0095005730500',
  '0264670973700',
  '0047463440000',
  '0239673830500',
  '0075180253500',
  '0032798685500',
  '0085968278000',
  '0107026424000',
  '0049923764000',
  '0025278186500',
  '0017593380000',
  '0023226218000',
  '0161387620500',
  '0078041605000',
  '0029029065000',
  '0097046680500',
  '0048890368000',
  '0255171136300',
  '0045003392500',
  '0191999440000',
  '0167964119400',
  '0049150598500',
  '0076246300000',
  '0084100468500',
  '0283401888500',
  '0045188262500',
  '0145718908000',
  '0033789100000',
  '0071448626500',
  '0101184240000',
  '0054844673000',
  '0164204945500',
  '0079864752500',
  '0074185220000',
  '0138879685000',
  '0065517501000',
  '0052678181500',
  ...])

In [ ]:
col_vals_as_strings = [str(abs(item)) if not (pd.isna(item) or np.isinf(item))  else None for item in df_pl[col_name].to_list()] # Treats np.inf as a missing value
# signs_of_items = [0 if item >= 0 else -1 for item in df_pl[col_name].to_list()]

In [141]:
signs_of_items_and_missing =  [
    None     if pd.isna(item)           else
    None     if not np.isfinite(item)   else   
    0        if item >= 0               else
    -1
    for item in df_pl[col_name].to_list()
]

In [115]:
digits_in_numbers, decimals_in_numbers = zip(*[tuple(item.split(".")) for item in col_vals_as_strings])

In [120]:
len_digits_in_numbers = [len(item) for item in digits_in_numbers]
n_digit_sub_cols = max(len_digits_in_numbers)
n_digit_sub_cols

5

In [121]:
len_decimals_in_numbers = [len(item) for item in decimals_in_numbers]
n_decimal_sub_cols = max(len_decimals_in_numbers)
n_decimal_sub_cols

6

In [122]:
n_sub_cols = n_digit_sub_cols + n_decimal_sub_cols + 1 # Adding one for a sub-column to store the sign
n_sub_cols

12

['16884', '17250', '23000', '70000', '00000', '00000']

In [116]:
[tuple(item.split(".")) for item in col_vals_as_strings]

[('16884', '924'),
 ('1725', '5523'),
 ('4449', '462'),
 ('21984', '47061'),
 ('3866', '8552'),
 ('3756', '6216'),
 ('8240', '5896'),
 ('7281', '5056'),
 ('6406', '4107'),
 ('28923', '13692'),
 ('2721', '3208'),
 ('27808', '7251'),
 ('1826', '843'),
 ('11090', '7178'),
 ('39611', '7577'),
 ('1837', '237'),
 ('10797', '3362'),
 ('2395', '17155'),
 ('10602', '385'),
 ('36837', '467'),
 ('13228', '84695'),
 ('4149', '736'),
 ('1252', '97273'),
 ('37701', '8768'),
 ('6203', '90175'),
 ('14001', '1338'),
 ('14451', '83515'),
 ('12268', '63225'),
 ('2775', '19215'),
 ('38711', '0'),
 ('35585', '576'),
 ('2198', '18985'),
 ('4687', '797'),
 ('13770', '0979'),
 ('48537', '480726'),
 ('1625', '43375'),
 ('15612', '19335'),
 ('2302', '3'),
 ('39774', '2763'),
 ('48173', '361'),
 ('3046', '062'),
 ('4949', '7587'),
 ('6272', '4772'),
 ('6313', '759'),
 ('6079', '6715'),
 ('20630', '28351'),
 ('3393', '35635'),
 ('3556', '9223'),
 ('12629', '8967'),
 ('38709', '176'),
 ('2211', '13075'),
 ('3579', '8287'),
 ('23568', '272'),
 ('37742', '5757'),
 ('8059', '6791'),
 ('47496', '49445'),
 ('13607', '36875'),
 ('34303', '1672'),
 ('23244', '7902'),
 ('5989', '52365'),
 ('8606', '2174'),
 ('4504', '6624'),
 ('30166', '61817'),
 ('4133', '64165'),
 ('14711', '7438'),
 ('1743', '214'),
 ('14235', '072'),
 ('6389', '37785'),
 ('5920', '1041'),
 ('17663', '1442'),
 ('16577', '7795'),
 ('6799', '458'),
 ('11741', '726'),
 ('11946', '6259'),
 ('7726', '854'),
 ('11356', '6609'),
 ('3947', '4131'),
 ('1532', '4697'),
 ('2755', '02095'),
 ('6571', '02435'),
 ('4441', '21315'),
 ('7935', '29115'),
 ('37165', '1638'),
 ('11033', '6617'),
 ('39836', '519'),
 ('21098', '55405'),
 ('43578', '9394'),
 ('11073', '176'),
 ('8026', '6666'),
 ('11082', '5772'),
 ('2026', '9741'),
 ('10942', '13205'),
 ('30184', '9367'),
 ('5729', '0053'),
 ('47291', '055'),
 ('3766', '8838'),
 ('12105', '32'),
 ('10226', '2842'),
 ('22412', '6485'),
 ('15820', '699'),
 ('6186', '127'),
 ('3645', '0894'),
 ('21344', '8467'),
 ('30942', '1918'),
 ('5003', '853'),
 ('17560', '37975'),
 ('2331', '519'),
 ('3877', '30425'),
 ('2867', '1196'),
 ('47055', '5321'),
 ('10825', '2537'),
 ('11881', '358'),
 ('4646', '759'),
 ('2404', '7338'),
 ('11488', '31695'),
 ('30259', '99556'),
 ('11381', '3254'),
 ('19107', '7796'),
 ('8601', '3293'),
 ('6686', '4313'),
 ('7740', '337'),
 ('1705', '6245'),
 ('2257', '47525'),
 ('39556', '4945'),
 ('10115', '00885'),
 ('3385', '39915'),
 ('17081', '08'),
 ('9634', '538'),
 ('32734', '1863'),
 ('6082', '405'),
 ('12815', '44495'),
 ('13616', '3586'),
 ('11163', '568'),
 ('1632', '56445'),
 ('2457', '21115'),
 ('2155', '6815'),
 ('1261', '442'),
 ('2045', '68525'),
 ('27322', '73386'),
 ('2166', '732'),
 ('27375', '90478'),
 ('3490', '5491'),
 ('18972', '495'),
 ('18157', '876'),
 ('20745', '9891'),
 ('5138', '2567'),
 ('40720', '55105'),
 ('9877', '6077'),
 ('10959', '6947'),
 ('1842', '519'),
 ('5125', '2157'),
 ('7789', '635'),
 ('6334', '34355'),
 ('19964', '7463'),
 ('7077', '1894'),
 ('6948', '7008'),
 ('21223', '6758'),
 ('15518', '18025'),
 ('36950', '2567'),
 ('19749', '38338'),
 ('21348', '706'),
 ('36149', '4835'),
 ('10450', '552'),
 ('5152', '134'),
 ('5028', '1466'),
 ('10407', '08585'),
 ('4830', '63'),
 ('6128', '79745'),
 ('2719', '27975'),
 ('4827', '90495'),
 ('13405', '3903'),
 ('8116', '68'),
 ('1694', '7964'),
 ('5246', '047'),
 ('2855', '43755'),
 ('48537', '480726'),
 ('6455', '86265'),
 ('10436', '096'),
 ('8823', '279'),
 ('8538', '28845'),
 ('11735', '87905'),
 ('1631', '8212'),
 ('4005', '4225'),
 ('7419', '4779'),
 ('7731', '4271'),
 ('43753', '33705'),
 ('3981', '9768'),
 ('5325', '651'),
 ('6775', '961'),
 ('4922', '9159'),
 ('12557', '6053'),
 ('4883', '866'),
 ('2137', '6536'),
 ('12044', '342'),
 ('1252', '97273'),
 ('1639', '5631'),
 ('5649', '715'),
 ('8516', '829'),
 ('9644', '2525'),
 ('14901', '5167'),
 ('2130', '6759'),
 ('8871', '1517'),
 ('13012', '20865'),
 ('37133', '8982'),
 ('7147', '105'),
 ('4337', '7352'),
 ('11743', '299'),
 ('20984', '0936'),
 ('13880', '949'),
 ('6610', '1097'),
 ('1980', '07'),
 ('8162', '71625'),
 ('3537', '703'),
 ('5002', '7827'),
 ('8520', '026'),
 ('7371', '772'),
 ('10355', '641'),
 ('2483', '736'),
 ('3392', '9768'),
 ('25081', '76784'),
 ('5012', '471'),
 ('10564', '8845'),
 ('5253', '524'),
 ('34779', '615'),
 ('19515', '5416'),
 ('11987', '1682'),
 ('2689', '4954'),
 ('24227', '33724'),
 ('7358', '17565'),
 ('9225', '2564'),
 ('7443', '64305'),
 ('14001', '2867'),
 ('1727', '785'),
 ('12333', '828'),
 ('6710', '1919'),
 ('19444', '2658'),
 ('1615', '7667'),
 ('4463', '2051'),
 ('17352', '6803'),
 ('7152', '6714'),
 ('38511', '6283'),
 ('5354', '07465'),
 ('35160', '13457'),
 ('7196', '867'),
 ('29523', '1656'),
 ('24476', '47851'),
 ('12648', '7034'),
 ('1986', '9334'),
 ('1832', '094'),
 ('4040', '55825'),
 ('12829', '4551'),
 ('47305', '305'),
 ('44260', '7499'),
 ('4260', '744'),
 ('41097', '16175'),
 ('13047', '33235'),
 ('43921', '1837'),
 ('5400', '9805'),
 ('11520', '09985'),
 ('33750', '2918'),
 ('11837', '16'),
 ('17085', '2676'),
 ('24869', '8368'),
 ('36219', '40545'),
 ('20462', '99766'),
 ('46151', '1245'),
 ('17179', '522'),
 ('14590', '63205'),
 ('7441', '053'),
 ('9282', '4806'),
 ('1719', '4363'),
 ('42856', '838'),
 ('7265', '7025'),
 ('9617', '66245'),
 ('2523', '1695'),
 ('9715', '841'),
 ('2803', '69785'),
 ('2150', '469'),
 ('12928', '7911'),
 ('9855', '1314'),
 ('22331', '5668'),
 ('48537', '480726'),
 ('4237', '12655'),
 ('11879', '10405'),
 ('9625', '92'),
 ('7742', '1098'),
 ('9432', '9253'),
 ('14256', '1928'),
 ('47896', '79135'),
 ('25992', '82104'),
 ('3172', '018'),
 ('20277', '80751'),
 ('42112', '2356'),
 ('2156', '7518'),
 ('3906', '127'),
 ('1704', '5681'),
 ('16297', '846'),
 ('21978', '6769'),
 ('38746', '3551'),
 ('9249', '4952'),
 ('6746', '7425'),
 ('24873', '3849'),
 ('12265', '5069'),
 ('4349', '462'),
 ('12646', '207'),
 ('19442', '3535'),
 ('20177', '67113'),
 ('4151', '0287'),
 ('11944', '59435'),
 ('7749', '1564'),
 ('8444', '474'),
 ('1737', '376'),
 ('42124', '5153'),
 ('8124', '4084'),
 ('34838', '873'),
 ('9722', '7695'),
 ('8835', '26495'),
 ('10435', '06525'),
 ('7421', '19455'),
 ('4667', '60765'),
 ('4894', '7533'),
 ('24671', '66334'),
 ('35491', '64'),
 ('11566', '30055'),
 ('2866', '091'),
 ('6600', '20595'),
 ('3561', '8889'),
 ('42760', '5022'),
 ('47928', '03'),
 ('9144', '565'),
 ('48517', '56315'),
 ('24393', '6224'),
 ('13429', '0354'),
 ('11658', '37915'),
 ('19144', '57652'),
 ('13822', '803'),
 ('12142', '5786'),
 ('13937', '6665'),
 ('41919', '097'),
 ('8232', '6388'),
 ('18955', '22017'),
 ('13352', '0998'),
 ('13217', '0945'),
 ('13981', '85035'),
 ('10977', '2063'),
 ('6184', '2994'),
 ('4889', '9995'),
 ('8334', '45755'),
 ('5478', '0368'),
 ('1635', '73365'),
 ('11830', '6072'),
 ('8932', '084'),
 ('3554', '203'),
 ('12404', '8791'),
 ('14133', '03775'),
 ('24603', '04837'),
 ('8944', '1151'),
 ('9620', '3307'),
 ('1837', '2819'),
 ('1607', '5101'),
 ('10043', '249'),
 ('4751', '07'),
 ('13844', '506'),
 ('2597', '779'),
 ('3180', '5101'),
 ('9778', '3472'),
 ('13430', '265'),
 ('8017', '06115'),
 ('8116', '26885'),
 ('3481', '868'),
 ('13415', '0381'),
 ('12029', '2867'),
 ('7639', '41745'),
 ('36085', '219'),
 ('1391', '5287'),
 ('18033', '9679'),
 ('21659', '9301'),
 ('38126', '2465'),
 ('16455', '70785'),
 ('27000', '98473'),
 ('15006', '57945'),
 ('42303', '69215'),
 ('20781', '48892'),
 ('5846', '9176'),
 ('8302', '53565'),
 ('1261', '859'),
 ('11856', '4115'),
 ('30284', '64294'),
 ('3176', '8159'),
 ('4618', '0799'),
 ('10736', '87075'),
 ('2138', '0707'),
 ('8964', '06055'),
 ('9290', '1395'),
 ('9411', '005'),
 ('7526', '70645'),
 ('8522', '003'),
 ('16586', '49771'),
 ('14988', '432'),
 ('1631', '6683'),
 ('9264', '797'),
 ('8083', '9198'),
 ('14692', '66935'),
 ('10269', '46'),
 ('3260', '199'),
 ('11396', '9002'),
 ('4185', '0979'),
 ('8539', '671'),
 ('6652', '5288'),
 ('4074', '4537'),
 ('1621', '3402'),
 ('19594', '80965'),
 ('14455', '64405'),
 ('5080', '096'),
 ('2134', '9015'),
 ('7345', '7266'),
 ('9140', '951'),
 ('18608', '262'),
 ('14418', '2804'),
 ('28950', '4692'),
 ('46889', '2612'),
 ('46599', '1084'),
 ('39125', '33225'),
 ('2727', '3951'),
 ('8968', '33'),
 ('9788', '8659'),
 ('6555', '07035'),
 ('7323', '734819'),
 ('3167', '45585'),
 ('18804', '7524'),
 ('23082', '95533'),
 ('4906', '40965'),
 ('5969', '723'),
 ('12638', '195'),
 ('4243', '59005'),
 ('13919', '8229'),
 ('2254', '7967'),
 ('5926', '846'),
 ('12592', '5345'),
 ('2897', '3235'),
 ('4738', '2682'),
 ('37079', '372'),
 ('1252', '97273'),
 ('28287', '89766'),
 ('26109', '32905'),
 ('7345', '084'),
 ('12730', '9996'),
 ('11454', '0215'),
 ('5910', '944'),
 ('4762', '329'),
 ('7512', '267'),
 ('4032', '2407'),
 ('1969', '614'),
 ('1769', '53165'),
 ('4686', '3887'),
 ('21797', '0004'),
 ('11881', '9696'),
 ('11840', '77505'),
 ('10601', '412'),
 ('7682', '67'),
 ('10381', '4787'),
 ('22144', '032'),
 ('15230', '32405'),
 ('11165', '41765'),
 ('1632', '03625'),
 ('19521', '9682'),
 ('13224', '693'),
 ('12643', '3778'),
 ('23288', '9284'),
 ('2201', '0971'),
 ('2497', '0383'),
 ('2203', '47185'),
 ('1744', '465'),
 ('20878', '78443'),
 ('25382', '297'),
 ('28868', '6639'),
 ('35147', '52848'),
 ('2534', '39375'),
 ('1534', '3045'),
 ('1824', '2854'),
 ('15555', '18875'),
 ('9304', '7019'),
 ('1622', '1885'),
 ('9880', '068'),
 ('9563', '029'),
 ('4347', '02335'),
 ('12475', '3513'),
 ('1253', '936'),
 ('48537', '480726'),
 ('10461', '9794'),
 ('1748', '774'),
 ('24513', '09126'),
 ('2196', '4732'),
 ('12574', '049'),
 ('17942', '106'),
 ('1967', '0227'),
 ('4931', '647'),
 ('8027', '968'),
 ('8211', '1002'),
 ('13470', '86'),
 ('36197', '699'),
 ('6837', '3687'),
 ('22218', '1149'),
 ('32548', '3405'),
 ('5974', '3847'),
 ('6796', '86325'),
 ('2643', '2685'),
 ('3077', '0955'),
 ('3044', '2133'),
 ('11455', '28'),
 ('11763', '0009'),
 ('2498', '4144'),
 ('9361', '3268'),
 ('1256', '299'),
 ('21082', '16'),
 ('11362', '755'),
 ('27724', '28875'),
 ('8413', '46305'),
 ('5240', '765'),
 ('3857', '75925'),
 ('25656', '57526'),
 ('3994', '1778'),
 ('9866', '30485'),
 ('5397', '6167'),
 ('38245', '59327'),
 ('11482', '63485'),
 ('24059', '68019'),
 ('9861', '025'),
 ('8342', '90875'),
 ('1708', '0014'),
 ('48537', '480726'),
 ('14043', '4767'),
 ('12925', '886'),
 ('19214', '70553'),
 ('13831', '1152'),
 ('6067', '12675'),
 ('5972', '378'),
 ('8825', '086'),
 ('8233', '0975'),
 ('27346', '04207'),
 ('6196', '448'),
 ('3056', '3881'),
 ('13887', '204'),
 ('48537', '480726'),
 ('10231', '4999'),
 ('23807', '2406'),
 ('3268', '84665'),
 ('11538', '421'),
 ('3213', '62205'),
 ('45863', '205'),
 ('13390', '559'),
 ('3972', '9247'),
 ('12957', '118'),
 ('11187', '6567'),
 ('17878', '90068'),
 ('3847', '674'),
 ('8334', '5896'),
 ('3935', '1799'),
 ('39983', '42595'),
 ('1646', '4297'),
 ('9193', '8385'),
 ('10923', '9332'),
 ('2494', '022'),
 ('9058', '7303'),
 ('2801', '2588'),
 ('2128', '43105'),
 ('6373', '55735'),
 ('7256', '7231'),
 ('11552', '904'),
 ('45702', '02235'),
 ('3761', '292'),
 ('2219', '4451'),
 ('4753', '6368'),
 ('31620', '00106'),
 ('13224', '05705'),
 ('12222', '8983'),
 ('1664', '9996'),
 ('48537', '480726'),
 ('9724', '53'),
 ('3206', '49135'),
 ('12913', '9924'),
 ('1639', '5631'),
 ('6356', '2707'),
 ('17626', '23951'),
 ('1252', '97273'),
 ('4779', '6023'),
 ('3861', '20965'),
 ('43943', '8761'),
 ('13635', '6379'),
 ('5976', '8311'),
 ('11842', '442'),
 ('8428', '0693'),
 ('2566', '4707'),
 ('15359', '1045'),
 ('5709', '1644'),
 ('8823', '98575'),
 ('7640', '3092'),
 ('5594', '8455'),
 ('7441', '501'),
 ('33471', '97189'),
 ('1633', '0444'),
 ('9174', '13565'),
 ('11070', '535'),
 ('16085', '1275'),
 ('17468', '9839'),
 ('9283', '562'),
 ('3558', '62025'),
 ('25678', '77845'),
 ('4435', '0942'),
 ('39241', '442'),
 ('8547', '6913'),
 ('6571', '544'),
 ('2207', '69745'),
 ('6753', '038'),
 ('1880', '07'),
 ('42969', '8527'),
 ('11658', '11505'),
 ('23306', '547'),
 ('34439', '8559'),
 ('10713', '644'),
 ('3659', '346'),
 ('40182', '246'),
 ('9182', '17'),
 ('34617', '84065'),
 ('12129', '61415'),
 ('3736', '4647'),
 ('6748', '5912'),
 ('11326', '71487'),
 ('11365', '952'),
 ('42983', '4585'),
 ('10085', '846'),
 ('1977', '815'),
 ('3366', '6697'),
 ('7173', '35995'),
 ('9391', '346'),
 ('14410', '9321'),
 ('2709', '1119'),
 ('24915', '04626'),
 ('20149', '3229'),
 ('12949', '1554'),
 ('6666', '243'),
 ('32787', '45859'),
 ('13143', '86485'),
 ('4466', '6214'),
 ('18806', '14547'),
 ('10141', '1362'),
 ('6123', '5688'),
 ('8252', '2843'),
 ('1712', '227'),
 ('12430', '95335'),
 ('9800', '8882'),
 ('10579', '711'),
 ('8280', '6227'),
 ('8527', '532'),
 ('12244', '531'),
 ('24667', '419'),
 ('3410', '324'),
 ('4058', '71245'),
 ('26392', '26029'),
 ('14394', '39815'),
 ('6435', '6237'),
 ('22192', '43711'),
 ('5148', '5526'),
 ('1252', '97273'),
 ('27037', '9141'),
 ('42560', '4304'),
 ('8703', '456'),
 ('40003', '33225'),
 ('45710', '20785'),
 ('6500', '2359'),
 ('4837', '5823'),
 ('3943', '5954'),
 ('4399', '731'),
 ('6185', '3208'),
 ('46200', '9851'),
 ('7222', '78625'),
 ('12485', '8009'),
 ('46130', '5265'),
 ('12363', '547'),
 ('10156', '7832'),
 ('2585', '269'),
 ('1252', '97273'),
 ('40103', '89'),
 ('9863', '4718'),
 ('4766', '022'),
 ('11244', '3769'),
 ('7729', '64575'),
 ('5438', '7491'),
 ('26236', '57997'),
 ('34806', '4677'),
 ('2104', '1134'),
 ('8068', '185'),
 ('2362', '22905'),
 ('2352', '96845'),
 ('3577', '999'),
 ('3201', '24515'),
 ('29186', '48236'),
 ('40273', '6455'),
 ('10976', '24575'),
 ('3500', '6123'),
 ('2020', '5523'),
 ('9541', '69555'),
 ('9504', '3103'),
 ('5385', '3379'),
 ('8930', '93455'),
 ('5375', '038'),
 ('44400', '4064'),
 ('10264', '4421'),
 ('6113', '23105'),
 ('5469', '0066'),
 ('1727', '54'),
 ('10107', '2206'),
 ('8310', '83915'),
 ('1984', '4533'),
 ('2457', '502'),
 ('12146', '971'),
 ('9566', '9909'),
 ('13112', '6048'),
 ('10848', '1343'),
 ('12231', '6136'),
 ('9875', '6804'),
 ('11264', '541'),
 ('12979', '358'),
 ('1263', '249'),
 ('10106', '13425'),
 ('40932', '4295'),
 ('6664', '68595'),
 ('16657', '71745'),
 ('2217', '6012'),
 ('6781', '3542'),
 ('19361', '9988'),
 ('10065', '413'),
 ('4234', '927'),
 ('9447', '25035'),
 ('14007', '222'),
 ('9583', '8933'),
 ('40419', '0191'),
 ('3484', '331'),
 ('36189', '1017'),
 ('44585', '45587'),
 ('8604', '48365'),
 ('18246', '4955'),
 ('43254', '41795'),
 ('3757', '8448'),
 ('8827', '2099'),
 ('9910', '35985'),
 ('11737', '84884'),
 ('1627', '28245'),
 ('8556', '907'),
 ('3062', '50825'),
 ('19539', '243'),
 ('1906', '35825'),
 ('14210', '53595'),
 ('11833', '7823'),
 ('17128', '42608'),
 ('5031', '26955'),
 ('7985', '815'),
 ('23065', '4207'),
 ('5428', '7277'),
 ('36307', '7983'),
 ('3925', '7582'),
 ('2416', '955'),
 ('19040', '876'),
 ('3070', '8087'),
 ('9095', '06825'),
 ('11842', '62375'),
 ('8062', '764'),
 ('7050', '642'),
 ('14319', '031'),
 ('6933', '24225'),
 ('27941', '28758'),
 ('11150', '78'),
 ('12797', '20962'),
 ('17748', '5062'),
 ('7261', '741'),
 ('10560', '4917'),
 ('6986', '697'),
 ('7448', '40395'),
 ('5934', '3798'),
 ('9869', '8102'),
 ('18259', '216'),
 ('1252', '97273'),
 ('9386', '1613'),
 ('24520', '264'),
 ('4350', '5144'),
 ('6414', '178'),
 ('12741', '16745'),
 ('1917', '3184'),
 ('5209', '57885'),
 ('13457', '9608'),
 ('5662', '225'),
 ('1252', '97273'),
 ('2731', '9122'),
 ('21195', '818'),
 ('7209', '4918'),
 ('18310', '742'),
 ('4266', '1658'),
 ('4719', '52405'),
 ('11848', '141'),
 ('17904', '52705'),
 ('7046', '7222'),
 ('14313', '8463'),
 ('2103', '08'),
 ('38792', '6856'),
 ('1815', '8759'),
 ('7731', '85785'),
 ('28476', '73499'),
 ('2136', '88225'),
 ('1252', '97273'),
 ('3309', '7926'),
 ('9414', '92'),
 ('6360', '9936'),
 ('11013', '7119'),
 ('4428', '88785'),
 ('5584', '3057'),
 ('1877', '9294'),
 ('2842', '76075'),
 ('3597', '596'),
 ('23401', '30575'),
 ('48537', '480726'),
 ('7445', '918'),
 ('2680', '9493'),
 ('1621', '8827'),
 ('8219', '2039'),
 ('12523', '6048'),
 ('16069', '08475'),
 ('43813', '8661'),
 ('20773', '62775'),
 ('39597', '4072'),
 ('6117', '4945'),
 ('13393', '756'),
 ('5266', '3656'),
 ('4719', '73655'),
 ('11743', '9341'),
 ('5377', '4578'),
 ('7160', '3303'),
 ('4402', '233'),
 ('11657', '7189'),
 ('6402', '29135'),
 ('12622', '1795'),
 ('1526', '312'),
 ('12323', '936'),
 ('36021', '0112'),
 ('27533', '9129'),
 ('10072', '05505'),
 ('45008', '9555'),
 ('9872', '701'),
 ('2438', '0552'),
 ('2974', '126'),
 ('10601', '63225'),
 ('37270', '1512'),
 ('14119', '62'),
 ('42111', '6647'),
 ('11729', '6795'),
 ('24106', '91255'),
 ('1875', '344'),
 ('40974', '1649'),
 ('15817', '9857'),
 ('18218', '16139'),
 ('10965', '446'),
 ('46113', '511'),
 ('7151', '092'),
 ('12269', '68865'),
 ('5458', '04645'),
 ('8782', '469'),
 ('6600', '361'),
 ('1252', '97273'),
 ('11576', '13'),
 ('13129', '60345'),
 ('4391', '652'),
 ('8457', '818'),
 ('3392', '3652'),
 ('5966', '8874'),
 ('6849', '026'),
 ('8891', '1395'),
 ('2690', '1138'),
 ('26140', '3603'),
 ('6653', '7886'),
 ('6282', '235'),
 ('6311', '952'),
 ('3443', '064'),
 ('2789', '0574'),
 ('2585', '85065'),
 ('46255', '1125'),
 ('4877', '98105'),
 ('19719', '6947'),
 ('27218', '43725'),
 ('5272', '1758'),
 ('1682', '597'),
 ('11945', '1327'),
 ('29330', '98315'),
 ('7243', '8136'),
 ('10422', '91665'),
 ('44202', '6536'),
 ('13555', '0049'),
 ('13063', '883'),
 ('19798', '05455'),
 ('2221', '56445'),
 ('1634', '5734'),
 ('2117', '33885'),
 ('8688', '85885'),
 ('48537', '480726'),
 ('4661', '28635'),
 ('8125', '7845'),
 ('12644', '589'),
 ('4564', '19145'),
 ('4846', '92015'),
 ('7633', '7206'),
 ('15170', '069'),
 ('17496', '306'),
 ('2639', '0429'),
 ('33732', '6867'),
 ('14382', '70905'),
 ('7626', '993'),
 ('5257', '50795'),
 ('2473', '3341'),
 ('21774', '32215'),
 ('35069', '37452'),
 ('13041', '921'),
 ('5245', '2269'),
 ('13451', '122'),
 ('13462', '52'),
 ('5488', '262'),
 ('4320', '41085'),
 ('6250', '435'),
 ('25333', '33284'),
 ('2913', '569'),
 ('12032', '326'),
 ('13470', '8044'),
 ('6289', '7549'),
 ('2927', '0647'),
 ('6238', '298'),
 ('10096', '97'),
 ('7348', '142'),
 ('4673', '3922'),
 ('12233', '828'),
 ('32108', '66282'),
 ('8965', '79575'),
 ('2304', '0022'),
 ('9487', '6442'),
 ('1252', '97273'),
 ('9549', '5651'),
 ('2217', '46915'),
 ('1628', '4709'),
 ('12982', '8747'),
 ('11674', '13'),
 ('7160', '094'),
 ('39047', '285'),
 ('6358', '77645'),
 ('19933', '458'),
 ('11534', '87265'),
 ('47462', '894'),
 ('4527', '18295'),
 ('38998', '546'),
 ('20009', '63365'),
 ('3875', '7341'),
 ('41999', '52'),
 ('12609', '88702'),
 ('41034', '2214'),
 ('28468', '91901'),
 ('2730', '10785'),
 ('3353', '284'),
 ('14474', '675'),
 ('9500', '57305'),
 ('26467', '09737'),
 ('4746', '344'),
 ('23967', '38305'),
 ('7518', '02535'),
 ('3279', '86855'),
 ('8596', '8278'),
 ('10702', '6424'),
 ('4992', '3764'),
 ('2527', '81865'),
 ('1759', '338'),
 ('2322', '6218'),
 ('16138', '76205'),
 ('7804', '1605'),
 ('2902', '9065'),
 ('9704', '66805'),
 ('4889', '0368'),
 ('25517', '11363'),
 ('4500', '33925'),
 ('19199', '944'),
 ('16796', '41194'),
 ('4915', '05985'),
 ('7624', '63'),
 ('8410', '04685'),
 ('28340', '18885'),
 ('4518', '82625'),
 ('14571', '8908'),
 ('3378', '91'),
 ('7144', '86265'),
 ('10118', '424'),
 ('5484', '4673'),
 ('16420', '49455'),
 ('7986', '47525'),
 ('7418', '522'),
 ('13887', '9685'),
 ('6551', '7501'),
 ('5267', '81815'),
 ...]

In [97]:
# Datetime